// src/routes/setup/[stage]/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import SetupTrainer from '$lib/components/board/SetupTrainer.svelte';
  import { SETUP_STAGES } from '$lib/components/board/SetupTrainer.svelte';

  let stageSlug = $derived(page.params.stage);
  let stageExists = $derived(SETUP_STAGES.some(s => s.slug === stageSlug));
</script>

{#if stageExists}
  <main class="page">
    <a href="/setup" class="back-link">&larr; Back to stages</a>
    <SetupTrainer {stageSlug} nextLabel="Back to Stages" nextHref="/setup" />
  </main>
{:else}
  <main class="page center">
    <h1>Stage not found</h1>
    <a href="/setup" class="muted-link">Back to stages</a>
  </main>
{/if}

<style>
  .page {
    min-height: 100vh;
    padding: 1.5rem;
    max-width: 48rem;
    margin: 0 auto;
  }
  .center { text-align: center; }
  .back-link {
    font-size: 0.875rem;
    color: var(--text-muted);
    display: inline-block;
    margin-bottom: 1rem;
  }
  .back-link:hover { color: var(--foreground); }
  .muted-link { color: var(--text-muted); }
  .muted-link:hover { text-decoration: underline; }
</style>

// src/app/setup/[stage]/page.tsx
"use client";

import { use } from "react";
import Link from "next/link";
import SetupTrainer, { SETUP_STAGES } from "@/components/board/SetupTrainer";

export default function SetupStagePage({
  params,
}: {
  params: Promise<{ stage: string }>;
}) {
  const { stage } = use(params);
  const idx = SETUP_STAGES.findIndex((s) => s.slug === stage);

  if (idx === -1) {
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto text-center">
        <h1 className="text-2xl font-bold mb-4">Stage not found</h1>
        <Link href="/setup" className="text-muted hover:underline">
          Back to stages
        </Link>
      </main>
    );
  }

  const stageInfo = SETUP_STAGES[idx];
  const nextStage =
    idx < SETUP_STAGES.length - 1 ? SETUP_STAGES[idx + 1] : null;

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link
        href="/setup"
        className="text-sm text-muted hover:text-foreground mb-4 inline-block"
      >
        &larr; Back to stages
      </Link>
      <SetupTrainer
        stageSlug={stageInfo.slug}
        nextLabel={nextStage ? `Next: ${nextStage.label}` : "Back to Stages"}
        nextHref={nextStage ? `/setup/${nextStage.slug}` : "/setup"}
      />
    </main>
  );
}
