// src/lib/components/blindfold/FlashPosition.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';

  const LIGHT = '#d4c4a0';
  const DARK = '#7a9e6e';

  type PieceColor = 'w' | 'b';
  type PieceKind = 'K' | 'Q' | 'R' | 'B' | 'N' | 'P';

  interface PiecePlacement {
    piece: PieceKind;
    color: PieceColor;
    square: string;
  }

  const PIECE_POOL: { piece: PieceKind; color: PieceColor }[] = [
    { piece: 'Q', color: 'w' }, { piece: 'R', color: 'w' }, { piece: 'R', color: 'w' },
    { piece: 'B', color: 'w' }, { piece: 'B', color: 'w' }, { piece: 'N', color: 'w' },
    { piece: 'N', color: 'w' }, { piece: 'P', color: 'w' },
    { piece: 'Q', color: 'b' }, { piece: 'R', color: 'b' }, { piece: 'R', color: 'b' },
    { piece: 'B', color: 'b' }, { piece: 'B', color: 'b' }, { piece: 'N', color: 'b' },
    { piece: 'N', color: 'b' }, { piece: 'P', color: 'b' },
  ];

  function randomSquare(): string {
    const f = Math.floor(Math.random() * 8);
    const r = Math.floor(Math.random() * 8);
    return String.fromCharCode(97 + f) + (r + 1);
  }

  function generatePosition(numPieces: number): PiecePlacement[] {
    const usedSquares = new Set<string>();
    const placements: PiecePlacement[] = [];

    let wkSq: string;
    do { wkSq = randomSquare(); } while (usedSquares.has(wkSq));
    usedSquares.add(wkSq);
    placements.push({ piece: 'K', color: 'w', square: wkSq });

    let bkSq: string;
    do { bkSq = randomSquare(); } while (usedSquares.has(bkSq));
    usedSquares.add(bkSq);
    placements.push({ piece: 'K', color: 'b', square: bkSq });

    for (let i = 2; i < numPieces; i++) {
      let sq: string;
      do { sq = randomSquare(); } while (usedSquares.has(sq));
      usedSquares.add(sq);
      const p = PIECE_POOL[Math.floor(Math.random() * PIECE_POOL.length)];
      placements.push({ ...p, square: sq });
    }

    return placements;
  }

  function sqToCoords(sq: string): [number, number] {
    return [sq.charCodeAt(0) - 97, 8 - parseInt(sq[1])];
  }

  const LEVELS = [
    { pieces: 4, time: 8000, label: '4 pieces' },
    { pieces: 6, time: 8000, label: '6 pieces' },
    { pieces: 8, time: 6000, label: '8 pieces' },
  ];

  const ROUNDS = 5;
  const SQ_SIZE = 40;
  const BOARD_PX = SQ_SIZE * 8;

  const TRAY_PIECES: { piece: PieceKind; color: PieceColor }[] = [
    { piece: 'K', color: 'w' }, { piece: 'Q', color: 'w' }, { piece: 'R', color: 'w' },
    { piece: 'B', color: 'w' }, { piece: 'N', color: 'w' }, { piece: 'P', color: 'w' },
    { piece: 'K', color: 'b' }, { piece: 'Q', color: 'b' }, { piece: 'R', color: 'b' },
    { piece: 'B', color: 'b' }, { piece: 'N', color: 'b' }, { piece: 'P', color: 'b' },
  ];

  type Phase = 'idle' | 'showing' | 'placing' | 'result' | 'done';

  let phase: Phase = $state('idle');
  let levelIdx = $state(0);
  let position: PiecePlacement[] = $state([]);
  let placed: PiecePlacement[] = $state([]);
  let selectedPiece: { piece: PieceKind; color: PieceColor } | null = $state(null);
  let round = $state(0);
  let totalCorrect = $state(0);
  let totalPieces = $state(0);
  let bestStars = $state(0);

  let showTimerRef: ReturnType<typeof setTimeout> | null = null;

  let level = $derived(LEVELS[levelIdx]);

  onMount(() => {
    bestStars = parseInt(localStorage.getItem('blindfold-flash-best-stars') ?? '0', 10);

    return () => {
      if (showTimerRef) clearTimeout(showTimerRef);
    };
  });

  function startRound() {
    const pos = generatePosition(level.pieces);
    position = pos;
    placed = [];
    selectedPiece = null;
    phase = 'showing';
    showTimerRef = setTimeout(() => {
      phase = 'placing';
    }, level.time);
  }

  function startGame() {
    round = 1;
    totalCorrect = 0;
    totalPieces = 0;
    startRound();
  }

  function handleBoardClick(e: MouseEvent) {
    if (phase !== 'placing' || !selectedPiece) return;
    const svg = e.currentTarget as SVGSVGElement;
    const rect = svg.getBoundingClientRect();
    const x = (e.clientX - rect.left) / rect.width * BOARD_PX;
    const y = (e.clientY - rect.top) / rect.height * BOARD_PX;
    const fi = Math.floor(x / SQ_SIZE);
    const ri = Math.floor(y / SQ_SIZE);
    if (fi >= 0 && fi < 8 && ri >= 0 && ri < 8) {
      const sq = String.fromCharCode(97 + fi) + (8 - ri);
      if (placed.some((p) => p.square === sq)) return;
      placed = [...placed, { ...selectedPiece, square: sq }];
    }
  }

  function checkAnswer() {
    let correctCount = 0;
    for (const p of placed) {
      const match = position.find(
        (orig) => orig.square === p.square && orig.piece === p.piece && orig.color === p.color
      );
      if (match) correctCount++;
    }
    totalCorrect += correctCount;
    totalPieces += position.length;
    phase = 'result';
  }

  function nextRound() {
    if (round >= ROUNDS) {
      const pct = totalPieces > 0 ? totalCorrect / totalPieces : 0;
      const stars = pct >= 0.9 ? 3 : pct >= 0.7 ? 2 : pct >= 0.4 ? 1 : 0;
      if (stars > bestStars) {
        localStorage.setItem('blindfold-flash-best-stars', String(stars));
        bestStars = stars;
      }
      phase = 'done';
      return;
    }
    round += 1;
    startRound();
  }

  function clearPlaced() {
    placed = [];
  }

  function goIdle() {
    phase = 'idle';
  }

  let correctSquares = $derived.by(() => {
    if (phase !== 'result') return new Set<string>();
    const s = new Set<string>();
    for (const p of placed) {
      const match = position.find(
        (orig) => orig.square === p.square && orig.piece === p.piece && orig.color === p.color
      );
      if (match) s.add(p.square);
    }
    return s;
  });

  let wrongSquares = $derived.by(() => {
    if (phase !== 'result') return new Set<string>();
    const s = new Set<string>();
    for (const p of placed) {
      const match = position.find(
        (orig) => orig.square === p.square && orig.piece === p.piece && orig.color === p.color
      );
      if (!match) s.add(p.square);
    }
    return s;
  });

  let overallStars = $derived.by(() => {
    if (totalPieces <= 0) return 0;
    const pct = totalCorrect / totalPieces;
    if (pct >= 0.9) return 3;
    if (pct >= 0.7) return 2;
    if (pct >= 0.4) return 1;
    return 0;
  });

  function boardFill(fi: number, ri: number, placedSqs?: Set<string>, wrongSqs?: Set<string>): string {
    const isLight = (fi + ri) % 2 === 0;
    const sqName = String.fromCharCode(97 + fi) + (8 - ri);
    if (placedSqs?.has(sqName)) return '#a3d9a3';
    if (wrongSqs?.has(sqName)) return '#f0a0a0';
    return isLight ? LIGHT : DARK;
  }
</script>

<div class="container">
  {#if phase === 'idle'}
    <div class="center-col">
      <h2 class="title">Flash Position</h2>
      <p class="muted">
        A position flashes briefly. Then place the pieces from memory! {ROUNDS} rounds.
      </p>
      <div class="level-picker">
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label class="level-label">Difficulty:</label>
        {#each LEVELS as l, i}
          <button
            class="level-btn"
            class:level-active={levelIdx === i}
            onclick={() => { levelIdx = i; }}
          >
            {l.label}
          </button>
        {/each}
      </div>
      {#if bestStars > 0}
        <div class="best">
          <StarRating stars={bestStars} size="sm" />
        </div>
      {/if}
      <button class="start-btn" onclick={startGame}>Start</button>
    </div>
  {:else if phase === 'done'}
    <div class="center-col">
      <h2 class="title">Complete!</h2>
      <p class="big-score">{totalCorrect}/{totalPieces} pieces correct</p>
      {#if overallStars > 0}
        <StarRating stars={overallStars} size="lg" />
      {/if}
      <button class="start-btn" onclick={goIdle}>Play Again</button>
    </div>
  {:else if phase === 'showing'}
    <div class="center-col">
      <div class="round-label">Round {round}/{ROUNDS} &mdash; Memorize!</div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg viewBox="0 0 {BOARD_PX} {BOARD_PX}" class="board-svg">
        {#each Array(8) as _, ri}
          {#each Array(8) as _, fi}
            <rect
              x={fi * SQ_SIZE}
              y={ri * SQ_SIZE}
              width={SQ_SIZE}
              height={SQ_SIZE}
              fill={boardFill(fi, ri)}
            />
          {/each}
        {/each}
        {#each position as p}
          {@const [f, r] = sqToCoords(p.square)}
          <image
            href="/pieces/{p.color}{p.piece}.svg"
            x={f * SQ_SIZE + SQ_SIZE * 0.1}
            y={r * SQ_SIZE + SQ_SIZE * 0.1}
            width={SQ_SIZE * 0.8}
            height={SQ_SIZE * 0.8}
          />
        {/each}
      </svg>
      <div class="studying">Studying...</div>
    </div>
  {:else if phase === 'result'}
    <div class="center-col">
      <div class="round-label">Round {round}/{ROUNDS}</div>
      <p class="result-count">{correctSquares.size}/{position.length} correct</p>
      <div class="muted-xs">Correct answer:</div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg viewBox="0 0 {BOARD_PX} {BOARD_PX}" class="board-svg">
        {#each Array(8) as _, ri}
          {#each Array(8) as _, fi}
            <rect
              x={fi * SQ_SIZE}
              y={ri * SQ_SIZE}
              width={SQ_SIZE}
              height={SQ_SIZE}
              fill={boardFill(fi, ri, correctSquares, wrongSquares)}
            />
          {/each}
        {/each}
        {#each position as p}
          {@const [f, r] = sqToCoords(p.square)}
          <image
            href="/pieces/{p.color}{p.piece}.svg"
            x={f * SQ_SIZE + SQ_SIZE * 0.1}
            y={r * SQ_SIZE + SQ_SIZE * 0.1}
            width={SQ_SIZE * 0.8}
            height={SQ_SIZE * 0.8}
          />
        {/each}
      </svg>
      <button class="action-btn" onclick={nextRound}>
        {round >= ROUNDS ? 'See Results' : 'Next'}
      </button>
    </div>
  {:else}
    <!-- placing phase -->
    <div class="placing-col">
      <div class="round-label">Round {round}/{ROUNDS} &mdash; Place from memory!</div>

      <div class="board-wrapper">
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions a11y_no_noninteractive_element_interactions -->
        <svg
          viewBox="0 0 {BOARD_PX} {BOARD_PX}"
          class="board-svg clickable"
          onclick={handleBoardClick}
        >
          {#each Array(8) as _, ri}
            {#each Array(8) as _, fi}
              <rect
                x={fi * SQ_SIZE}
                y={ri * SQ_SIZE}
                width={SQ_SIZE}
                height={SQ_SIZE}
                fill={boardFill(fi, ri)}
              />
            {/each}
          {/each}
          {#each placed as p}
            {@const [f, r] = sqToCoords(p.square)}
            <image
              href="/pieces/{p.color}{p.piece}.svg"
              x={f * SQ_SIZE + 4}
              y={r * SQ_SIZE + 4}
              width={32}
              height={32}
            />
          {/each}
        </svg>
      </div>

      <div class="tray">
        {#each TRAY_PIECES as p}
          {@const isSelected = selectedPiece?.piece === p.piece && selectedPiece?.color === p.color}
          <button
            class="tray-btn"
            class:tray-selected={isSelected}
            onclick={() => { selectedPiece = isSelected ? null : p; }}
          >
            <img src="/pieces/{p.color}{p.piece}.svg" alt="{p.color}{p.piece}" class="tray-img" />
          </button>
        {/each}
      </div>

      <div class="actions">
        <button class="clear-btn" onclick={clearPlaced}>Clear</button>
        <button class="action-btn" onclick={checkAnswer}>
          Check ({placed.length}/{level.pieces})
        </button>
      </div>
    </div>
  {/if}
</div>

<style>
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    max-width: 32rem;
    margin: 0 auto;
  }

  .center-col {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    text-align: center;
  }

  .placing-col {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .title {
    font-size: 1.25rem;
    font-weight: bold;
  }

  .muted {
    color: var(--text-muted);
  }

  .muted-xs {
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .best {
    font-size: 0.875rem;
    color: var(--text-faint);
  }

  .round-label {
    font-size: 0.875rem;
    color: var(--text-faint);
  }

  .level-picker {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .level-label {
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .level-btn {
    padding: 0.25rem 0.75rem;
    border-radius: 0.5rem;
    font-size: 0.875rem;
    font-weight: 500;
    border: 1px solid var(--card-border);
    background: transparent;
    color: var(--text-faint);
    cursor: pointer;
    transition: color 0.15s, border-color 0.15s;
  }

  .level-btn:hover {
    color: var(--foreground);
  }

  .level-active {
    background: #16a34a;
    color: white;
    border-color: #16a34a;
  }

  .start-btn {
    padding: 0.75rem 2rem;
    background: rgba(255, 248, 230, 0.15);
    color: var(--foreground);
    border: none;
    border-radius: 0.5rem;
    font-weight: bold;
    font-size: 1.125rem;
    cursor: pointer;
    transition: background 0.15s;
  }

  .start-btn:hover {
    background: rgba(255, 248, 230, 0.25);
  }

  .big-score {
    font-size: 1.875rem;
    font-weight: bold;
  }

  .result-count {
    font-weight: bold;
  }

  .board-svg {
    width: 100%;
    max-width: 280px;
    display: block;
  }

  @media (min-width: 640px) {
    .board-svg {
      max-width: 320px;
    }
  }

  .clickable {
    cursor: pointer;
  }

  .board-wrapper {
    position: relative;
  }

  .studying {
    font-size: 0.875rem;
    color: var(--text-muted);
    animation: pulse 2s ease-in-out infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }

  .tray {
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    gap: 0.25rem;
  }

  .tray-btn {
    width: 2.5rem;
    height: 2.5rem;
    border-radius: 0.25rem;
    border: 2px solid var(--card-border);
    background: transparent;
    cursor: pointer;
    padding: 0;
    transition: border-color 0.15s;
  }

  .tray-btn:hover {
    border-color: rgba(255, 248, 230, 0.3);
  }

  .tray-selected {
    border-color: #22c55e;
    background: rgba(34, 197, 94, 0.2);
  }

  .tray-img {
    width: 100%;
    height: 100%;
    display: block;
  }

  .actions {
    display: flex;
    gap: 0.75rem;
  }

  .clear-btn {
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    border: 1px solid var(--card-border);
    background: transparent;
    color: var(--text-faint);
    font-size: 0.875rem;
    cursor: pointer;
    transition: color 0.15s;
  }

  .clear-btn:hover {
    color: var(--foreground);
  }

  .action-btn {
    padding: 0.5rem 1.5rem;
    background: #16a34a;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.15s;
  }

  .action-btn:hover {
    background: #15803d;
  }
</style>

// src/components/blindfold/FlashPosition.tsx
"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import StarRating from "@/components/puzzle/StarRating";

const LIGHT = "#d4c4a0";
const DARK = "#7a9e6e";

type PieceColor = "w" | "b";
type PieceKind = "K" | "Q" | "R" | "B" | "N" | "P";

interface PiecePlacement {
  piece: PieceKind;
  color: PieceColor;
  square: string;
}

const PIECE_POOL: { piece: PieceKind; color: PieceColor }[] = [
  { piece: "Q", color: "w" }, { piece: "R", color: "w" }, { piece: "R", color: "w" },
  { piece: "B", color: "w" }, { piece: "B", color: "w" }, { piece: "N", color: "w" },
  { piece: "N", color: "w" }, { piece: "P", color: "w" },
  { piece: "Q", color: "b" }, { piece: "R", color: "b" }, { piece: "R", color: "b" },
  { piece: "B", color: "b" }, { piece: "B", color: "b" }, { piece: "N", color: "b" },
  { piece: "N", color: "b" }, { piece: "P", color: "b" },
];

function randomSquare(): string {
  const f = Math.floor(Math.random() * 8);
  const r = Math.floor(Math.random() * 8);
  return String.fromCharCode(97 + f) + (r + 1);
}

function generatePosition(numPieces: number): PiecePlacement[] {
  const usedSquares = new Set<string>();
  const placements: PiecePlacement[] = [];

  // Always include both kings
  let wkSq: string;
  do { wkSq = randomSquare(); } while (usedSquares.has(wkSq));
  usedSquares.add(wkSq);
  placements.push({ piece: "K", color: "w", square: wkSq });

  let bkSq: string;
  do { bkSq = randomSquare(); } while (usedSquares.has(bkSq));
  usedSquares.add(bkSq);
  placements.push({ piece: "K", color: "b", square: bkSq });

  // Fill remaining with random pieces
  for (let i = 2; i < numPieces; i++) {
    let sq: string;
    do { sq = randomSquare(); } while (usedSquares.has(sq));
    usedSquares.add(sq);
    const p = PIECE_POOL[Math.floor(Math.random() * PIECE_POOL.length)];
    placements.push({ ...p, square: sq });
  }

  return placements;
}

function sqToCoords(sq: string): [number, number] {
  return [sq.charCodeAt(0) - 97, 8 - parseInt(sq[1])];
}

function PositionBoard({ placements, size, placedSquares, wrongSquares }: {
  placements: PiecePlacement[];
  size: number;
  placedSquares?: Set<string>;
  wrongSquares?: Set<string>;
}) {
  const S = size;
  const B = S * 8;

  return (
    <svg viewBox={`0 0 ${B} ${B}`} className="w-full max-w-[280px] sm:max-w-[320px]">
      {Array.from({ length: 8 }, (_, ri) =>
        Array.from({ length: 8 }, (_, fi) => {
          const isLight = (fi + ri) % 2 === 0;
          const sqName = String.fromCharCode(97 + fi) + (8 - ri);
          let fill = isLight ? LIGHT : DARK;
          if (placedSquares?.has(sqName)) fill = "#a3d9a3";
          if (wrongSquares?.has(sqName)) fill = "#f0a0a0";
          return <rect key={`${fi}-${ri}`} x={fi * S} y={ri * S} width={S} height={S} fill={fill} />;
        })
      )}
      {placements.map((p, i) => {
        const [f, r] = sqToCoords(p.square);
        return (
          <image
            key={i}
            href={`/pieces/${p.color}${p.piece}.svg`}
            x={f * S + S * 0.1}
            y={r * S + S * 0.1}
            width={S * 0.8}
            height={S * 0.8}
          />
        );
      })}
    </svg>
  );
}

const LEVELS = [
  { pieces: 4, time: 8000, label: "4 pieces" },
  { pieces: 6, time: 8000, label: "6 pieces" },
  { pieces: 8, time: 6000, label: "8 pieces" },
];

type Phase = "idle" | "showing" | "placing" | "result" | "done";

export default function FlashPosition() {
  const [phase, setPhase] = useState<Phase>("idle");
  const [levelIdx, setLevelIdx] = useState(0);
  const [position, setPosition] = useState<PiecePlacement[]>([]);
  const [placed, setPlaced] = useState<PiecePlacement[]>([]);
  const [selectedPiece, setSelectedPiece] = useState<{ piece: PieceKind; color: PieceColor } | null>(null);
  const [round, setRound] = useState(0);
  const [totalCorrect, setTotalCorrect] = useState(0);
  const [totalPieces, setTotalPieces] = useState(0);
  const [bestStars, setBestStars] = useState(0);
  const showTimerRef = useRef<ReturnType<typeof setTimeout>>(null);

  const ROUNDS = 5;
  const level = LEVELS[levelIdx];

  useEffect(() => {
    setBestStars(parseInt(localStorage.getItem("blindfold-flash-best-stars") ?? "0", 10));
  }, []);

  useEffect(() => {
    return () => {
      if (showTimerRef.current) clearTimeout(showTimerRef.current);
    };
  }, []);

  const startRound = useCallback(() => {
    const pos = generatePosition(level.pieces);
    setPosition(pos);
    setPlaced([]);
    setSelectedPiece(null);
    setPhase("showing");
    showTimerRef.current = setTimeout(() => {
      setPhase("placing");
    }, level.time);
  }, [level]);

  const startGame = useCallback(() => {
    setRound(1);
    setTotalCorrect(0);
    setTotalPieces(0);
    startRound();
  }, [startRound]);

  const handleBoardClick = useCallback(
    (sq: string) => {
      if (phase !== "placing" || !selectedPiece) return;
      // Don't place on already-placed square
      if (placed.some((p) => p.square === sq)) return;
      setPlaced((prev) => [...prev, { ...selectedPiece, square: sq }]);
    },
    [phase, selectedPiece, placed],
  );

  const checkAnswer = useCallback(() => {
    let correct = 0;
    for (const p of placed) {
      const match = position.find(
        (orig) => orig.square === p.square && orig.piece === p.piece && orig.color === p.color
      );
      if (match) correct++;
    }
    setTotalCorrect((c) => c + correct);
    setTotalPieces((t) => t + position.length);
    setPhase("result");
  }, [placed, position]);

  const nextRound = useCallback(() => {
    if (round >= ROUNDS) {
      const pct = totalPieces > 0 ? totalCorrect / totalPieces : 0;
      const stars = pct >= 0.9 ? 3 : pct >= 0.7 ? 2 : pct >= 0.4 ? 1 : 0;
      if (stars > bestStars) {
        localStorage.setItem("blindfold-flash-best-stars", String(stars));
        setBestStars(stars);
      }
      setPhase("done");
      return;
    }
    setRound((r) => r + 1);
    startRound();
  }, [round, totalCorrect, totalPieces, bestStars, startRound]);

  // Compute result data
  const correctSquares = new Set<string>();
  const wrongSquares = new Set<string>();
  if (phase === "result") {
    for (const p of placed) {
      const match = position.find(
        (orig) => orig.square === p.square && orig.piece === p.piece && orig.color === p.color
      );
      if (match) correctSquares.add(p.square);
      else wrongSquares.add(p.square);
    }
  }

  const overallStars = totalPieces > 0
    ? (totalCorrect / totalPieces >= 0.9 ? 3 : totalCorrect / totalPieces >= 0.7 ? 2 : totalCorrect / totalPieces >= 0.4 ? 1 : 0)
    : 0;

  // Piece tray for placing
  const TRAY_PIECES: { piece: PieceKind; color: PieceColor }[] = [
    { piece: "K", color: "w" }, { piece: "Q", color: "w" }, { piece: "R", color: "w" },
    { piece: "B", color: "w" }, { piece: "N", color: "w" }, { piece: "P", color: "w" },
    { piece: "K", color: "b" }, { piece: "Q", color: "b" }, { piece: "R", color: "b" },
    { piece: "B", color: "b" }, { piece: "N", color: "b" }, { piece: "P", color: "b" },
  ];

  if (phase === "idle") {
    return (
      <div className="flex flex-col items-center gap-6 max-w-md mx-auto text-center">
        <h2 className="text-xl font-bold">Flash Position</h2>
        <p className="text-muted">
          A position flashes briefly. Then place the pieces from memory! {ROUNDS} rounds.
        </p>
        <div className="flex items-center gap-4">
          <label className="text-sm text-muted">Difficulty:</label>
          {LEVELS.map((l, i) => (
            <button
              key={i}
              onClick={() => setLevelIdx(i)}
              className={`px-3 py-1 rounded-lg text-sm font-medium transition-colors ${
                levelIdx === i ? "bg-green-600 text-white" : "border border-card-border text-faint hover:text-foreground"
              }`}
            >
              {l.label}
            </button>
          ))}
        </div>
        {bestStars > 0 && (
          <div className="text-sm text-faint">
            <StarRating stars={bestStars} size="sm" />
          </div>
        )}
        <button
          onClick={startGame}
          className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold text-lg hover:bg-green-700 transition-colors"
        >
          Start
        </button>
      </div>
    );
  }

  if (phase === "done") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <h2 className="text-xl font-bold">Complete!</h2>
        <p className="text-3xl font-bold">{totalCorrect}/{totalPieces} pieces correct</p>
        {overallStars > 0 && <StarRating stars={overallStars} size="lg" />}
        <button
          onClick={() => setPhase("idle")}
          className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition-colors"
        >
          Play Again
        </button>
      </div>
    );
  }

  if (phase === "showing") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <div className="text-sm text-faint">Round {round}/{ROUNDS} — Memorize!</div>
        <PositionBoard placements={position} size={40} />
        <div className="text-sm text-muted animate-pulse">Studying...</div>
      </div>
    );
  }

  if (phase === "result") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <div className="text-sm text-faint">Round {round}/{ROUNDS}</div>
        <p className="font-bold">{correctSquares.size}/{position.length} correct</p>
        <div className="text-xs text-muted">Correct answer:</div>
        <PositionBoard placements={position} size={40} placedSquares={correctSquares} wrongSquares={wrongSquares} />
        <button
          onClick={nextRound}
          className="px-6 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
        >
          {round >= ROUNDS ? "See Results" : "Next"}
        </button>
      </div>
    );
  }

  // placing phase
  return (
    <div className="flex flex-col items-center gap-4 max-w-lg mx-auto">
      <div className="text-sm text-faint">Round {round}/{ROUNDS} — Place from memory!</div>

      {/* Board for placing */}
      <div className="relative">
        <svg
          viewBox="0 0 320 320"
          className="w-full max-w-[280px] sm:max-w-[320px] cursor-pointer"
          onClick={(e) => {
            const svg = e.currentTarget;
            const rect = svg.getBoundingClientRect();
            const x = (e.clientX - rect.left) / rect.width * 320;
            const y = (e.clientY - rect.top) / rect.height * 320;
            const fi = Math.floor(x / 40);
            const ri = Math.floor(y / 40);
            if (fi >= 0 && fi < 8 && ri >= 0 && ri < 8) {
              const sq = String.fromCharCode(97 + fi) + (8 - ri);
              handleBoardClick(sq);
            }
          }}
        >
          {Array.from({ length: 8 }, (_, ri) =>
            Array.from({ length: 8 }, (_, fi) => {
              const isLight = (fi + ri) % 2 === 0;
              return <rect key={`${fi}-${ri}`} x={fi * 40} y={ri * 40} width={40} height={40} fill={isLight ? LIGHT : DARK} />;
            })
          )}
          {placed.map((p, i) => {
            const [f, r] = sqToCoords(p.square);
            return (
              <image
                key={i}
                href={`/pieces/${p.color}${p.piece}.svg`}
                x={f * 40 + 4}
                y={r * 40 + 4}
                width={32}
                height={32}
              />
            );
          })}
        </svg>
      </div>

      {/* Piece tray */}
      <div className="grid grid-cols-6 gap-1">
        {TRAY_PIECES.map((p) => {
          const isSelected = selectedPiece?.piece === p.piece && selectedPiece?.color === p.color;
          return (
            <button
              key={`${p.color}${p.piece}`}
              onClick={() => setSelectedPiece(isSelected ? null : p)}
              className={`w-10 h-10 rounded border-2 transition-colors ${
                isSelected ? "border-green-500 bg-green-600/20" : "border-card-border hover:border-foreground/30"
              }`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={`/pieces/${p.color}${p.piece}.svg`} alt={`${p.color}${p.piece}`} className="w-full h-full" />
            </button>
          );
        })}
      </div>

      <div className="flex gap-3">
        <button
          onClick={() => setPlaced([])}
          className="px-4 py-2 rounded-lg border border-card-border text-faint hover:text-foreground transition-colors text-sm"
        >
          Clear
        </button>
        <button
          onClick={checkAnswer}
          className="px-6 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
        >
          Check ({placed.length}/{level.pieces})
        </button>
      </div>
    </div>
  );
}
