// src/routes/learn/[piece]/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';
  import { getPuzzlesForPiece, PIECES, getCategory } from '$lib/puzzles';
  import { progressState, isPuzzleUnlocked, getPuzzleProgress } from '$lib/state/progress-store';
  import EndgameShell from '$lib/components/endgame/EndgameShell.svelte';
  import MateTrainer from '$lib/components/endgame/MateTrainer.svelte';
  import type { MateEndgameType } from '$lib/logic/endgame';
  import type { PiecePlacement } from '$lib/logic/types';
  import { SECTIONS as HOW_TO_WIN_SECTIONS, getSectionSteps } from '$lib/components/lessons/how-to-win-data';
  import type { HowToWinSection } from '$lib/components/lessons/how-to-win-data';
  import ColorOfSquare from '$lib/components/blindfold/ColorOfSquare.svelte';
  import SameDiagonal from '$lib/components/blindfold/SameDiagonal.svelte';
  import SameRankFile from '$lib/components/blindfold/SameRankFile.svelte';
  import MoveCounting from '$lib/components/blindfold/MoveCounting.svelte';
  import KnightRoutes from '$lib/components/blindfold/KnightRoutes.svelte';
  import BishopRoutes from '$lib/components/blindfold/BishopRoutes.svelte';
  import PieceReachability from '$lib/components/blindfold/PieceReachability.svelte';
  import NeighborSquares from '$lib/components/blindfold/NeighborSquares.svelte';
  import RelativePosition from '$lib/components/blindfold/RelativePosition.svelte';
  import WhatChanged from '$lib/components/blindfold/WhatChanged.svelte';
  import WhereDidItLand from '$lib/components/blindfold/WhereDidItLand.svelte';
  import FlashPosition from '$lib/components/blindfold/FlashPosition.svelte';
  import PieceCount from '$lib/components/blindfold/PieceCount.svelte';
  import RookMaze from '$lib/components/blindfold/RookMaze.svelte';
  import BlindTactics from '$lib/components/blindfold/BlindTactics.svelte';
  import BlindfoldPuzzle from '$lib/components/blindfold/BlindfoldPuzzle.svelte';
  import KnightGauntlet from '$lib/components/blindfold/KnightGauntlet.svelte';
  import GuardingGame from '$lib/components/blindfold/GuardingGame.svelte';
  import KnightSquares from '$lib/components/blindfold/KnightSquares.svelte';
  import BlindfoldMate from '$lib/components/blindfold/BlindfoldMate.svelte';

  let piece = $derived(page.params.piece ?? '');

  // Endgame positions
  const ENDGAME_POSITIONS: Record<string, { title: string; instruction: string; placements: PiecePlacement[] }> = {
    'endings-kpk': {
      title: 'King + Pawn vs King',
      instruction: 'Promote the pawn! Every wrong move is a draw.',
      placements: [
        { piece: 'K', color: 'w', square: 'd6' },
        { piece: 'P', color: 'w', square: 'd4' },
        { piece: 'K', color: 'b', square: 'd8' },
      ],
    },
  };

  let endgame = $derived(ENDGAME_POSITIONS[piece]);
  let mateEndgameMatch = $derived(piece.match(/^endings-(kqk|krrk|krk|kbbk)$/));
  let howToWinMatch = $derived(piece.match(/^how-to-win-(check|checkmate|stalemate)$/));
  let blindfoldMateMatch = $derived(piece.match(/^blindfold-mate-(kqk|krrk|krk|kbbk)$/));

  const BLINDFOLD_ROUTES: Record<string, any> = {
    'blindfold-color': ColorOfSquare,
    'blindfold-diagonals': SameDiagonal,
    'blindfold-rankfile': SameRankFile,
    'blindfold-counting': MoveCounting,
    'blindfold-knight-routes': KnightRoutes,
    'blindfold-bishop-routes': BishopRoutes,
    'blindfold-reachability': PieceReachability,
    'blindfold-neighbors': NeighborSquares,
    'blindfold-relative': RelativePosition,
    'blindfold-changed': WhatChanged,
    'blindfold-landed': WhereDidItLand,
    'blindfold-flash': FlashPosition,
    'blindfold-piececount': PieceCount,
    'blindfold-rookmaze': RookMaze,
    'blindfold-blindtactics': BlindTactics,
    'blindfold-puzzle': BlindfoldPuzzle,
    'blindfold-gauntlet': KnightGauntlet,
    'blindfold-guarding': GuardingGame,
    'blindfold-knightsquares': KnightSquares,
  };
  let BlindfoldComponent = $derived(BLINDFOLD_ROUTES[piece]);

  // Category page
  let category = $derived(getCategory(piece));

  // Puzzle list
  let puzzleSet = $derived(getPuzzlesForPiece(piece));
  let pieceInfo = $derived(PIECES.find((p) => p.key === piece));

  // How to Win section stars
  let sectionStars = $state<Record<string, number>>({});
  let hwStepStars = $state(0);
  onMount(() => {
    const s: Record<string, number> = {};
    for (const sec of HOW_TO_WIN_SECTIONS) {
      s[sec.key] = parseInt(localStorage.getItem(sec.storageKey) ?? '0', 10);
    }
    sectionStars = s;
    if (howToWinMatch) {
      const sectionInfo = HOW_TO_WIN_SECTIONS.find(s => s.key === howToWinMatch![1]);
      if (sectionInfo) {
        hwStepStars = parseInt(localStorage.getItem(sectionInfo.storageKey) ?? '0', 10);
      }
    }
  });

  let parentCategory = $derived(
    piece.startsWith('checkmate-') ? 'checkmate'
    : piece.startsWith('tactics-') ? 'tactics'
    : piece.startsWith('endings-') ? 'endings'
    : piece.startsWith('blindfold-') ? 'blindfold'
    : null
  );
  let backHref = $derived(
    parentCategory === 'blindfold' ? '/vision'
    : parentCategory ? `/learn/${parentCategory}`
    : '/'
  );
  let backLabel = $derived(
    parentCategory === 'blindfold' ? 'Back to vision'
    : parentCategory ? `Back to ${parentCategory}`
    : 'Back to home'
  );

  // Redirect /learn/blindfold to /vision
  $effect(() => {
    if (piece === 'blindfold') {
      goto('/vision', { replaceState: true });
    }
  });

  let displayName = $derived(pieceInfo?.name ?? puzzleSet?.name ?? 'Puzzles');
  let displayDescription = $derived(pieceInfo?.description ?? '');
  let displayIcon = $derived(pieceInfo?.icon ?? (piece === 'danger-zones' ? '/pieces/bN.svg' : '/pieces/wQ.svg'));
  let puzzleIds = $derived(puzzleSet?.puzzles.map((p) => p.id) ?? []);
</script>

{#if endgame}
  <!-- Endgame trainer (e.g. KPK) -->
  <main class="page">
    <a href="/learn/endings" class="back-link">&larr; Back to endings</a>
    <EndgameShell title={endgame.title} instruction={endgame.instruction} placements={endgame.placements} />
  </main>
{:else if mateEndgameMatch}
  <!-- Mate conversion trainer (KQK, KRRK, etc.) -->
  <main class="page">
    <a href="/learn/endings" class="back-link">&larr; Back to endings</a>
    <MateTrainer type={mateEndgameMatch[1] as MateEndgameType} />
  </main>
{:else if piece === 'how-to-win'}
  <!-- How to Win hub page -->
  <main class="page">
    <a href="/" class="back-link">&larr; Back to home</a>

    <div class="page-header">
      <img src="/pieces/wK.svg" alt="How to Win" class="header-icon" />
      <div>
        <h1>How to Win</h1>
        <p class="muted">Learn check, checkmate, and stalemate.</p>
      </div>
    </div>

    <div class="subcategory-list">
      {#each HOW_TO_WIN_SECTIONS as sec}
        <a href="/learn/how-to-win-{sec.key}" class="sub-item">
          <div class="sub-left">
            <img src={sec.icon} alt={sec.title} class="sub-icon" />
            <div>
              <h3>{sec.title}</h3>
              <p class="sub-desc">{sec.description}</p>
            </div>
          </div>
          <div class="sub-right">
            {#if (sectionStars[sec.key] ?? 0) > 0}
              <StarRating stars={sectionStars[sec.key]} size="sm" />
            {/if}
          </div>
        </a>
      {/each}
    </div>
  </main>
{:else if howToWinMatch}
  <!-- How to Win section page (check/checkmate/stalemate) -->
  {@const section = howToWinMatch[1] as HowToWinSection}
  {@const sectionInfo = HOW_TO_WIN_SECTIONS.find(s => s.key === section)}
  {@const steps = getSectionSteps(section)}
  <main class="page">
    <a href="/learn/how-to-win" class="back-link">&larr; Back to How to Win</a>

    {#if sectionInfo && steps}
      <div class="page-header">
        <img src={sectionInfo.icon} alt={sectionInfo.title} class="header-icon" />
        <div>
          <h1>{sectionInfo.title}</h1>
          <p class="muted">{sectionInfo.description}</p>
        </div>
      </div>

      <a href="/learn/{piece}/{steps[0].slug}" class="start-btn">
        {hwStepStars > 0 ? 'Play Again' : 'Start'}
      </a>

      {#if hwStepStars > 0}
        <div class="stars-center">
          <StarRating stars={hwStepStars} size="sm" />
        </div>
      {/if}

      <div class="puzzle-list">
        {#each steps as step, idx}
          <a href="/learn/{piece}/{step.slug}" class="puzzle-item">
            <div class="puzzle-left">
              <span class="puzzle-num">{idx + 1}.</span>
              <div>
                <span class="puzzle-title">{step.title}</span>
                <p class="puzzle-instruction">{step.instruction}</p>
              </div>
            </div>
          </a>
        {/each}
      </div>
    {/if}
  </main>
{:else if BlindfoldComponent}
  <!-- Blindfold trainer -->
  <main class={['page', piece !== 'blindfold-guarding' && 'blindfold-page', piece === 'blindfold-guarding' && 'blindfold-wide']}>
    <a href="/vision" class="back-link">&larr; Back to vision</a>
    <BlindfoldComponent />
  </main>
{:else if blindfoldMateMatch}
  <!-- Blindfold mate trainer -->
  <main class="page blindfold-page">
    <a href="/vision" class="back-link">&larr; Back to vision</a>
    <BlindfoldMate type={blindfoldMateMatch[1] as MateEndgameType} />
  </main>
{:else if category}
  <!-- Category page with subcategories -->
  <main class="page">
    <a href="/practice" class="back-link">&larr; Back to practice</a>

    <div class="page-header">
      <img src={category.icon} alt={category.name} class="header-icon" />
      <div>
        <h1>{category.name}</h1>
        <p class="muted">{category.description}</p>
      </div>
    </div>

    <div class="subcategory-list">
      {#each category.subcategories as sub}
        {@const subSet = getPuzzlesForPiece(sub.key)}
        {@const total = subSet?.puzzles.length ?? 0}
        {@const completed = $progressState.loaded ? (subSet?.puzzles.filter(p => getPuzzleProgress(p.id)?.completed).length ?? 0) : 0}
        {@const bestStars = $progressState.loaded && subSet ? Math.max(0, ...subSet.puzzles.map(p => getPuzzleProgress(p.id)?.bestStars ?? 0)) : 0}
        {#if sub.comingSoon}
          <div class="sub-item disabled">
            <div class="sub-left">
              <img src={sub.icon} alt={sub.name} class="sub-icon" />
              <div>
                <h3>{sub.name}</h3>
                <p class="sub-desc">{sub.description}</p>
              </div>
            </div>
            <span class="coming-soon">Coming soon</span>
          </div>
        {:else}
          <a href="/learn/{sub.key}" class="sub-item">
            <div class="sub-left">
              <img src={sub.icon} alt={sub.name} class="sub-icon" />
              <div>
                <h3>{sub.name}</h3>
                <p class="sub-desc">{sub.description}</p>
              </div>
            </div>
            <div class="sub-right">
              <span class="stat">{completed}/{total}</span>
              {#if completed > 0 && completed === total}
                <StarRating stars={bestStars} size="sm" />
              {/if}
            </div>
          </a>
        {/if}
      {/each}
    </div>
  </main>
{:else if puzzleSet}
  <!-- Puzzle list page -->
  <main class="page">
    <a href={backHref} class="back-link">&larr; {backLabel}</a>

    <div class="page-header">
      <img src={displayIcon} alt={displayName} class="header-icon" />
      <div>
        <h1>{displayName} Puzzles</h1>
        {#if displayDescription}<p class="muted">{displayDescription}</p>{/if}
      </div>
    </div>

    <div class="puzzle-list">
      {#each puzzleSet.puzzles as puzz, idx}
        {@const unlocked = $progressState.loaded && isPuzzleUnlocked(puzz.id, puzzleIds)}
        {@const progress = getPuzzleProgress(puzz.id)}
        {#if unlocked}
          <a href="/learn/{piece}/{puzz.id}" class="puzzle-item">
            <div class="puzzle-left">
              <span class="puzzle-num">{idx + 1}.</span>
              <div>
                <span class="puzzle-title">{puzz.title}</span>
                <p class="puzzle-instruction">{puzz.instruction}</p>
              </div>
            </div>
            {#if progress?.completed}
              <StarRating stars={progress.bestStars} size="sm" />
            {/if}
          </a>
        {:else}
          <div class="puzzle-item locked">
            <div class="puzzle-left">
              <span class="puzzle-num">{idx + 1}.</span>
              <span class="puzzle-title">{puzz.title}</span>
            </div>
            <span class="locked-label">Locked</span>
          </div>
        {/if}
      {/each}
    </div>
  </main>
{:else}
  <main class="page center">
    <h1>Not found</h1>
    <a href="/" class="muted-link">Back to home</a>
  </main>
{/if}

<style>
  .page { min-height: 100vh; padding: 1.5rem; max-width: 42rem; margin: 0 auto; }
  .center { text-align: center; }
  .back-link { font-size: 0.875rem; color: var(--text-muted); display: inline-block; margin-bottom: 1rem; }
  .back-link:hover { color: var(--foreground); }
  .muted { color: var(--text-muted); }
  .muted-link { color: var(--text-muted); }
  .muted-link:hover { text-decoration: underline; }

  .page-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 2rem; }
  .page-header h1 { font-size: 1.875rem; font-weight: bold; }
  .header-icon { width: 4rem; height: 4rem; }

  /* Subcategory list */
  .subcategory-list { display: flex; flex-direction: column; gap: 0.75rem; }
  .sub-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.25rem;
    border-radius: 0.75rem;
    border: 1px solid var(--card-border);
    background: var(--card-bg);
    transition: all 0.15s;
  }
  .sub-item:not(.disabled):hover {
    border-color: rgba(240, 230, 204, 0.3);
    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
  }
  .sub-item.disabled { opacity: 0.4; }
  .sub-left { display: flex; align-items: center; gap: 1rem; }
  .sub-icon { width: 2.5rem; height: 2.5rem; }
  .sub-left h3 { font-weight: bold; }
  .sub-desc { font-size: 0.875rem; color: var(--text-muted); }
  .sub-right { text-align: right; }
  .stat { font-size: 0.75rem; color: var(--text-faint); }
  .coming-soon { font-size: 0.75rem; color: var(--text-faint); }

  /* Puzzle list */
  .puzzle-list { display: flex; flex-direction: column; gap: 0.5rem; }
  .puzzle-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem;
    border-radius: 0.5rem;
    border: 1px solid var(--card-border);
    background: var(--card-bg);
    transition: all 0.15s;
  }
  .puzzle-item:not(.locked):hover {
    border-color: rgba(240, 230, 204, 0.3);
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  }
  .puzzle-item.locked { opacity: 0.4; }
  .puzzle-left { display: flex; align-items: center; gap: 0.75rem; }
  .puzzle-num { font-size: 0.875rem; color: var(--text-faint); width: 1.5rem; text-align: right; }
  .puzzle-title { font-weight: 500; }
  .puzzle-instruction { font-size: 0.75rem; color: var(--text-faint); }
  .locked-label { font-size: 0.75rem; color: var(--text-faint); }

  /* How to Win section */
  .start-btn {
    display: block;
    margin-bottom: 1rem;
    padding: 0.75rem 1rem;
    border-radius: 0.75rem;
    background: #16a34a;
    color: white;
    text-align: center;
    font-weight: bold;
    font-size: 1.125rem;
    text-decoration: none;
    transition: background 0.15s;
  }
  .start-btn:hover { background: #15803d; }
  .stars-center { margin-bottom: 1rem; text-align: center; }
  .blindfold-page { max-width: 42rem; margin: 0 auto; }
  .blindfold-wide { max-width: 64rem; margin: 0 auto; }
</style>

// src/app/learn/[piece]/page.tsx
"use client";

import { use, useState, useEffect } from "react";
import Link from "next/link";
import { getPuzzlesForPiece, PIECES, getCategory } from "@/lib/puzzles";
import { useProgress } from "@/lib/state/progress-context";
import StarRating from "@/components/puzzle/StarRating";
import EndgameShell from "@/components/endgame/EndgameShell";
import MateTrainer from "@/components/endgame/MateTrainer";
import ColorOfSquare from "@/components/blindfold/ColorOfSquare";
import SameDiagonal from "@/components/blindfold/SameDiagonal";
import KnightRoutes from "@/components/blindfold/KnightRoutes";
import GuardingGame from "@/components/blindfold/GuardingGame";
import BlindfoldMate from "@/components/blindfold/BlindfoldMate";
import type { MateEndgameType } from "@/lib/logic/endgame";
import PolgarTrainer from "@/components/polgar/PolgarTrainer";
import { SECTIONS as HOW_TO_WIN_SECTIONS, getSectionSteps } from "@/components/lessons/HowToWinLesson";
import type { HowToWinSection } from "@/components/lessons/HowToWinLesson";
import type { PiecePlacement } from "@/lib/logic/types";

const ENDGAME_POSITIONS: Record<string, { title: string; instruction: string; placements: PiecePlacement[] }> = {
  "endings-kpk": {
    title: "King + Pawn vs King",
    instruction: "Promote the pawn! Every wrong move is a draw.",
    placements: [
      { piece: "K", color: "w", square: "d6" },
      { piece: "P", color: "w", square: "d4" },
      { piece: "K", color: "b", square: "d8" },
    ],
  },
};

export default function PieceLearnPage({
  params,
}: {
  params: Promise<{ piece: string }>;
}) {
  const { piece } = use(params);

  // Check for endgame trainers
  const endgame = ENDGAME_POSITIONS[piece];
  if (endgame) {
    return (
      <main className="min-h-screen p-4">
        <Link
          href="/learn/endings"
          className="text-sm text-muted hover:text-foreground mb-2 inline-block ml-4"
        >
          &larr; Back to endings
        </Link>
        <EndgameShell
          title={endgame.title}
          instruction={endgame.instruction}
          placements={endgame.placements}
        />
      </main>
    );
  }

  // Check for mate conversion trainers
  const mateEndgameMatch = piece.match(/^endings-(kqk|krrk|krk|kbbk)$/);
  if (mateEndgameMatch) {
    const endgameType = mateEndgameMatch[1] as MateEndgameType;
    return (
      <main className="min-h-screen p-4">
        <Link
          href="/learn/endings"
          className="text-sm text-muted hover:text-foreground mb-2 inline-block ml-4"
        >
          &larr; Back to endings
        </Link>
        <MateTrainer type={endgameType} />
      </main>
    );
  }

  // Check for blindfold trainers
  if (piece === "blindfold-color") {
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto">
        <Link href="/learn/blindfold" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to blindfold
        </Link>
        <ColorOfSquare />
      </main>
    );
  }
  if (piece === "blindfold-diagonals") {
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto">
        <Link href="/learn/blindfold" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to blindfold
        </Link>
        <SameDiagonal />
      </main>
    );
  }
  if (piece === "blindfold-knight-routes") {
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto">
        <Link href="/learn/blindfold" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to blindfold
        </Link>
        <KnightRoutes />
      </main>
    );
  }
  if (piece === "blindfold-guarding") {
    return (
      <main className="min-h-screen p-6 max-w-5xl mx-auto">
        <Link href="/learn/blindfold" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to blindfold
        </Link>
        <GuardingGame />
      </main>
    );
  }
  const blindfoldMateMatch = piece.match(/^blindfold-mate-(kqk|krrk|krk|kbbk)$/);
  if (blindfoldMateMatch) {
    const endgameType = blindfoldMateMatch[1] as MateEndgameType;
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto">
        <Link href="/learn/blindfold" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to blindfold
        </Link>
        <BlindfoldMate type={endgameType} />
      </main>
    );
  }

  // How to Win hub page
  if (piece === "how-to-win") {
    return <HowToWinHub />;
  }

  // How to Win sub-sections — show step list
  const howToWinMatch = piece.match(/^how-to-win-(check|checkmate|stalemate)$/);
  if (howToWinMatch) {
    const section = howToWinMatch[1] as HowToWinSection;
    return <HowToWinSectionPage section={section} />;
  }

  // Polgar mate trainers
  const mateMap: Record<string, "mate-in-1" | "mate-in-2" | "mate-in-3"> = {
    "mate-in-one": "mate-in-1",
    "mate-in-two": "mate-in-2",
    "mate-in-three": "mate-in-3",
  };
  if (piece in mateMap) {
    const mateType = mateMap[piece];
    return (
      <main className="min-h-screen p-6 max-w-2xl mx-auto">
        <Link href="/" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to home
        </Link>
        <PolgarTrainer type={mateType} />
      </main>
    );
  }

  // Check if this is a category page
  const category = getCategory(piece);
  if (category) {
    return <CategoryPage categoryKey={piece} />;
  }

  return <PuzzleListPage pieceKey={piece} />;
}

function CategoryPage({ categoryKey }: { categoryKey: string }) {
  const category = getCategory(categoryKey)!;
  const { state, getPuzzleProgress } = useProgress();

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link href="/" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
        &larr; Back to home
      </Link>

      <div className="flex items-center gap-4 mb-8">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={category.icon} alt={category.name} className="w-16 h-16" />
        <div>
          <h1 className="text-3xl font-bold">{category.name}</h1>
          <p className="text-muted">{category.description}</p>
        </div>
      </div>

      <div className="space-y-3">
        {category.subcategories.map((sub) => {
          const puzzleSet = getPuzzlesForPiece(sub.key);
          const totalPuzzles = puzzleSet?.puzzles.length ?? 0;
          let completedPuzzles = 0;
          let bestStars = 0;

          if (puzzleSet && state.loaded) {
            for (const p of puzzleSet.puzzles) {
              const progress = getPuzzleProgress(p.id);
              if (progress?.completed) {
                completedPuzzles++;
                bestStars = Math.max(bestStars, progress.bestStars);
              }
            }
          }

          if (sub.comingSoon) {
            return (
              <div
                key={sub.key}
                className="flex items-center justify-between p-5 rounded-xl border border-card-border opacity-40"
              >
                <div className="flex items-center gap-4">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={sub.icon} alt={sub.name} className="w-10 h-10" />
                  <div>
                    <h3 className="font-bold">{sub.name}</h3>
                    <p className="text-sm text-muted">{sub.description}</p>
                  </div>
                </div>
                <span className="text-xs text-faint">Coming soon</span>
              </div>
            );
          }

          return (
            <Link
              key={sub.key}
              href={`/learn/${sub.key}`}
              className="flex items-center justify-between p-5 rounded-xl border border-card-border bg-card hover:border-foreground/30 hover:shadow-lg transition-all"
            >
              <div className="flex items-center gap-4">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={sub.icon} alt={sub.name} className="w-10 h-10" />
                <div>
                  <h3 className="font-bold">{sub.name}</h3>
                  <p className="text-sm text-muted">{sub.description}</p>
                </div>
              </div>
              <div className="text-right">
                <span className="text-xs text-faint">{completedPuzzles}/{totalPuzzles}</span>
                {completedPuzzles > 0 && completedPuzzles === totalPuzzles && (
                  <div className="mt-1"><StarRating stars={bestStars} size="sm" /></div>
                )}
              </div>
            </Link>
          );
        })}
      </div>
    </main>
  );
}

function PuzzleListPage({ pieceKey }: { pieceKey: string }) {
  const puzzleSet = getPuzzlesForPiece(pieceKey);
  const pieceInfo = PIECES.find((p) => p.key === pieceKey);
  const { state, isPuzzleUnlocked, getPuzzleProgress } = useProgress();

  // For sub-categories, find the parent category for back-navigation
  const parentCategory = pieceKey.startsWith("checkmate-")
    ? "checkmate"
    : pieceKey.startsWith("tactics-")
      ? "tactics"
      : pieceKey.startsWith("endings-")
        ? "endings"
        : pieceKey.startsWith("blindfold-")
          ? "blindfold"
          : null;
  const backHref = parentCategory ? `/learn/${parentCategory}` : "/";
  const backLabel = parentCategory ? `Back to ${parentCategory}` : "Back to home";

  // Get display info — either from PIECES or from the puzzle set itself
  const displayName = pieceInfo?.name ?? puzzleSet?.name ?? "Puzzles";
  const displayDescription = pieceInfo?.description ?? "";
  const displayIcon = pieceInfo?.icon ?? "/pieces/wQ.svg";

  if (!puzzleSet) {
    return (
      <main className="min-h-screen p-6 max-w-4xl mx-auto text-center">
        <h1 className="text-2xl font-bold mb-4">Not found</h1>
        <Link href="/" className="text-muted hover:underline">Back to home</Link>
      </main>
    );
  }

  const puzzleIds = puzzleSet.puzzles.map((p) => p.id);

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link href={backHref} className="text-sm text-muted hover:text-foreground mb-4 inline-block">
        &larr; {backLabel}
      </Link>

      <div className="flex items-center gap-4 mb-8">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={displayIcon} alt={displayName} className="w-16 h-16" />
        <div>
          <h1 className="text-3xl font-bold">{displayName} Puzzles</h1>
          {displayDescription && <p className="text-muted">{displayDescription}</p>}
        </div>
      </div>

      <div className="space-y-2">
        {puzzleSet.puzzles.map((puzzle, idx) => {
          const unlocked = state.loaded && isPuzzleUnlocked(puzzle.id, puzzleIds);
          const progress = getPuzzleProgress(puzzle.id);

          return (
            <div key={puzzle.id}>
              {unlocked ? (
                <Link
                  href={`/learn/${pieceKey}/${puzzle.id}`}
                  className="flex items-center justify-between p-4 rounded-lg border border-card-border bg-card hover:border-foreground/30 hover:shadow transition-all"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-sm text-faint w-6 text-right">{idx + 1}.</span>
                    <div>
                      <span className="font-medium">{puzzle.title}</span>
                      <p className="text-xs text-faint">{puzzle.instruction}</p>
                    </div>
                  </div>
                  {progress?.completed && (
                    <StarRating stars={progress.bestStars} size="sm" />
                  )}
                </Link>
              ) : (
                <div className="flex items-center justify-between p-4 rounded-lg border border-card-border opacity-40">
                  <div className="flex items-center gap-3">
                    <span className="text-sm text-faint w-6 text-right">{idx + 1}.</span>
                    <span className="font-medium">{puzzle.title}</span>
                  </div>
                  <span className="text-xs text-faint">Locked</span>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </main>
  );
}

function HowToWinHub() {
  const [stars, setStars] = useState<Record<string, number>>({});
  useEffect(() => {
    const s: Record<string, number> = {};
    for (const sec of HOW_TO_WIN_SECTIONS) {
      s[sec.key] = parseInt(localStorage.getItem(sec.storageKey) ?? "0", 10);
    }
    setStars(s);
  }, []);

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link href="/" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
        &larr; Back to home
      </Link>

      <div className="flex items-center gap-4 mb-8">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/pieces/wK.svg" alt="How to Win" className="w-16 h-16" />
        <div>
          <h1 className="text-3xl font-bold">How to Win</h1>
          <p className="text-muted">Learn check, checkmate, and stalemate.</p>
        </div>
      </div>

      <div className="space-y-3">
        {HOW_TO_WIN_SECTIONS.map((sec) => (
          <Link
            key={sec.key}
            href={`/learn/how-to-win-${sec.key}`}
            className="flex items-center justify-between p-5 rounded-xl border border-card-border bg-card hover:border-foreground/30 hover:shadow-lg transition-all"
          >
            <div className="flex items-center gap-4">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={sec.icon} alt={sec.title} className="w-10 h-10" />
              <div>
                <h3 className="font-bold">{sec.title}</h3>
                <p className="text-sm text-muted">{sec.description}</p>
              </div>
            </div>
            <div className="text-right">
              {(stars[sec.key] ?? 0) > 0 && <StarRating stars={stars[sec.key]} size="sm" />}
            </div>
          </Link>
        ))}
      </div>
    </main>
  );
}

function HowToWinSectionPage({ section }: { section: HowToWinSection }) {
  const sectionInfo = HOW_TO_WIN_SECTIONS.find(s => s.key === section)!;
  const steps = getSectionSteps(section);
  const [sectionStars, setSectionStars] = useState(0);
  useEffect(() => {
    setSectionStars(parseInt(localStorage.getItem(sectionInfo.storageKey) ?? "0", 10));
  }, [sectionInfo.storageKey]);

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link href="/learn/how-to-win" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
        &larr; Back to How to Win
      </Link>

      <div className="flex items-center gap-4 mb-6">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={sectionInfo.icon} alt={sectionInfo.title} className="w-16 h-16" />
        <div>
          <h1 className="text-3xl font-bold">{sectionInfo.title}</h1>
          <p className="text-muted">{sectionInfo.description}</p>
        </div>
      </div>

      {/* Start from beginning */}
      <Link
        href={`/learn/how-to-win-${section}/${steps[0].slug}`}
        className="block mb-4 py-3 px-4 rounded-xl bg-green-600 hover:bg-green-700 transition-colors text-white text-center font-bold text-lg"
      >
        {sectionStars > 0 ? "Play Again" : "Start"}
      </Link>

      {sectionStars > 0 && (
        <div className="mb-4 text-center">
          <StarRating stars={sectionStars} size="sm" />
        </div>
      )}

      {/* Individual steps */}
      <div className="space-y-2">
        {steps.map((step, idx) => (
          <Link
            key={step.slug}
            href={`/learn/how-to-win-${section}/${step.slug}`}
            className="flex items-center gap-3 p-4 rounded-lg border border-card-border bg-card hover:border-foreground/30 hover:shadow transition-all"
          >
            <span className="text-sm text-faint w-6 text-right">{idx + 1}.</span>
            <div>
              <span className="font-medium">{step.title}</span>
              <p className="text-xs text-faint">{step.instruction}</p>
            </div>
          </Link>
        ))}
      </div>
    </main>
  );
}
