// src/components/game/GameViewer.tsx
"use client";

import { useState, useMemo, useEffect, useCallback, useRef } from "react";
import Board from "@/components/board/Board";
import { parsePgn } from "@/lib/logic/pgn";
import { getLegalMoves } from "@/lib/logic/attacks";
import { ModelGame } from "@/lib/games/types";
import { SquareId, PieceColor } from "@/lib/logic/types";
import type { Arrow } from "@/lib/logic/pgn";

const AUTOPLAY_MS = 1200;

export default function GameViewer({ game }: { game: ModelGame }) {
  const parsed = useMemo(() => parsePgn(game.pgn), [game.pgn]);

  const [currentMove, setCurrentMove] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const moveListRef = useRef<HTMLDivElement>(null);

  // Test mode state
  const [testMode, setTestMode] = useState(false);
  const [testMoveIdx, setTestMoveIdx] = useState(0);
  const [testSelected, setTestSelected] = useState<SquareId | null>(null);
  const [testHintArrow, setTestHintArrow] = useState<Arrow | null>(null);
  const [testComplete, setTestComplete] = useState(false);

  const board = testMode
    ? parsed.positions[testMoveIdx]
    : parsed.positions[currentMove];
  const lastMove = currentMove > 0 ? parsed.moves[currentMove - 1] : null;
  const totalMoves = parsed.moves.length;
  const currentComment = lastMove?.comment;
  const currentArrows = lastMove?.arrows;

  const testColorToMove: PieceColor = testMoveIdx % 2 === 0 ? "w" : "b";

  const testValidMoves = useMemo(() => {
    if (!testMode || !testSelected || testComplete) return [];
    return getLegalMoves(testSelected, parsed.positions[testMoveIdx], testColorToMove);
  }, [testMode, testSelected, testMoveIdx, testComplete, parsed.positions, testColorToMove]);

  const [testDragFrom, setTestDragFrom] = useState<SquareId | null>(null);
  const testDragMoves = useMemo(() => {
    if (!testMode || !testDragFrom || testComplete) return [];
    return getLegalMoves(testDragFrom, parsed.positions[testMoveIdx], testColorToMove);
  }, [testMode, testDragFrom, testMoveIdx, testComplete, parsed.positions, testColorToMove]);

  const advanceTestMove = useCallback((from: SquareId, to: SquareId) => {
    const expected = parsed.moves[testMoveIdx];
    if (from === expected.from && to === expected.to) {
      setTestHintArrow(null);
      const next = testMoveIdx + 1;
      if (next >= totalMoves) {
        setTestMoveIdx(next);
        setTestComplete(true);
      } else {
        setTestMoveIdx(next);
      }
      setTestSelected(null);
    } else {
      // Wrong move — show hint arrow
      setTestHintArrow({ from: expected.from, to: expected.to, color: "#15803d" });
      setTestSelected(null);
    }
  }, [parsed.moves, testMoveIdx, totalMoves]);

  const handleTestClick = useCallback((sq: SquareId) => {
    if (testComplete) return;
    const currentBoard = parsed.positions[testMoveIdx];

    if (!testSelected) {
      const p = currentBoard.pieces.get(sq);
      if (p && p.color === testColorToMove) {
        setTestSelected(sq);
        setTestHintArrow(null);
      }
      return;
    }

    if (sq === testSelected) {
      setTestSelected(null);
      return;
    }

    // Clicking another own piece
    const target = currentBoard.pieces.get(sq);
    if (target && target.color === testColorToMove) {
      setTestSelected(sq);
      return;
    }

    // Try to move
    const legal = getLegalMoves(testSelected, currentBoard, testColorToMove);
    if (!legal.includes(sq)) {
      setTestSelected(null);
      return;
    }

    advanceTestMove(testSelected, sq);
  }, [testComplete, testSelected, testMoveIdx, testColorToMove, parsed.positions, advanceTestMove]);

  const handleTestDrop = useCallback((from: SquareId, to: SquareId) => {
    if (testComplete || from === to) return;
    const currentBoard = parsed.positions[testMoveIdx];
    const p = currentBoard.pieces.get(from);
    if (!p || p.color !== testColorToMove) return;
    const legal = getLegalMoves(from, currentBoard, testColorToMove);
    if (!legal.includes(to)) return;
    advanceTestMove(from, to);
  }, [testComplete, testMoveIdx, testColorToMove, parsed.positions, advanceTestMove]);

  const handleTestDragStart = useCallback((sq: SquareId) => {
    if (testComplete) return;
    setTestDragFrom(sq);
    setTestHintArrow(null);
  }, [testComplete]);

  const handleTestDragEnd = useCallback(() => {
    setTestDragFrom(null);
  }, []);

  const startTestMode = useCallback(() => {
    setTestMode(true);
    setTestMoveIdx(0);
    setTestSelected(null);
    setTestHintArrow(null);
    setTestComplete(false);
    setIsPlaying(false);
  }, []);

  const exitTestMode = useCallback(() => {
    setTestMode(false);
    setTestSelected(null);
    setTestHintArrow(null);
    setTestComplete(false);
    setCurrentMove(0);
  }, []);

  const goForward = useCallback(
    () => setCurrentMove(m => Math.min(m + 1, totalMoves)),
    [totalMoves],
  );
  const goBack = useCallback(
    () => setCurrentMove(m => Math.max(m - 1, 0)),
    [],
  );

  // Auto-play
  useEffect(() => {
    if (testMode) return;
    if (!isPlaying || currentMove >= totalMoves) return;
    const timer = setTimeout(() => {
      setCurrentMove(m => {
        const next = m + 1;
        if (next >= totalMoves) setIsPlaying(false);
        return next;
      });
    }, AUTOPLAY_MS);
    return () => clearTimeout(timer);
  }, [testMode, isPlaying, currentMove, totalMoves]);

  // Keyboard controls
  useEffect(() => {
    if (testMode) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") { e.preventDefault(); goBack(); }
      else if (e.key === "ArrowRight") { e.preventDefault(); goForward(); }
      else if (e.key === " ") { e.preventDefault(); setIsPlaying(p => !p); }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [testMode, goBack, goForward]);

  // Scroll current move into view within the move list (not the page)
  useEffect(() => {
    if (testMode) return;
    const container = moveListRef.current;
    if (!container) return;
    const highlighted = container.querySelector("[data-active='true']") as HTMLElement | null;
    if (!highlighted) return;
    const top = highlighted.offsetTop - container.offsetTop;
    const bottom = top + highlighted.offsetHeight;
    if (top < container.scrollTop) {
      container.scrollTop = top;
    } else if (bottom > container.scrollTop + container.clientHeight) {
      container.scrollTop = bottom - container.clientHeight;
    }
  }, [testMode, currentMove]);

  // Build move pairs for display (SAN + optional NAG like "!" or "!!")
  const movePairs: { num: number; white: string; black?: string }[] = [];
  for (let i = 0; i < totalMoves; i += 2) {
    const wm = parsed.moves[i];
    const bm = parsed.moves[i + 1];
    movePairs.push({
      num: Math.floor(i / 2) + 1,
      white: wm.san + (wm.nag ?? ""),
      black: bm ? bm.san + (bm.nag ?? "") : undefined,
    });
  }

  const noop = useCallback(() => {}, []);

  // Test mode rendering
  if (testMode) {
    const moveNum = Math.floor(testMoveIdx / 2) + 1;
    const isWhiteTurn = testMoveIdx % 2 === 0;
    const statusText = testComplete
      ? "You did it! You reproduced the entire game."
      : `Move ${moveNum}${isWhiteTurn ? "." : "..."} ${isWhiteTurn ? "White" : "Black"} to play`;

    return (
      <div className="flex flex-col items-center gap-4 max-w-4xl mx-auto">
        <div className="text-center">
          <h2 className="text-xl font-bold mb-1">Test Mode</h2>
          <p className="text-muted">{statusText}</p>
        </div>

        <div className="w-full max-w-[560px]">
          {/* Black player (top) */}
          <div className="flex items-center gap-2 mb-1 px-1">
            <div className="w-3 h-3 rounded-full bg-[#1a1a1a] border border-foreground/30" />
            <span className="text-sm text-muted">{game.black}</span>
          </div>

          <Board
            board={board}
            selectedSquare={testSelected}
            validMoves={testValidMoves}
            targets={[]}
            reachedTargets={[]}
            dragValidMoves={testDragMoves}
            onSquareClick={handleTestClick}
            onDrop={handleTestDrop}
            onDragStart={handleTestDragStart}
            onDragEnd={handleTestDragEnd}
            playableColors={["w", "b"]}
            arrows={testHintArrow ? [testHintArrow] : undefined}
          />

          {/* White player (bottom) */}
          <div className="flex items-center gap-2 mt-1 px-1">
            <div className="w-3 h-3 rounded-full bg-white border border-foreground/30" />
            <span className="text-sm text-muted">{game.white}</span>
          </div>
        </div>

        <div className="flex gap-3">
          {testComplete && (
            <button
              onClick={() => { setTestMoveIdx(0); setTestComplete(false); setTestHintArrow(null); }}
              className="px-5 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
            >
              Try Again
            </button>
          )}
          <button
            onClick={exitTestMode}
            className="px-5 py-2 rounded-lg border border-card-border bg-card hover:bg-btn-hover transition-colors"
          >
            Back to Viewer
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col lg:flex-row gap-6 items-start max-w-4xl mx-auto">
      {/* Board side */}
      <div className="flex-1 w-full lg:max-w-[560px]">
        {/* Black player (top) */}
        <div className="flex items-center gap-2 mb-1 px-1">
          <div className="w-3 h-3 rounded-full bg-[#1a1a1a] border border-foreground/30" />
          <span className="text-sm text-muted">{game.black}</span>
        </div>

        <Board
          board={board}
          selectedSquare={null}
          validMoves={[]}
          targets={[]}
          reachedTargets={[]}
          dragValidMoves={[]}
          onSquareClick={noop}
          onDrop={noop}
          onDragStart={noop}
          onDragEnd={noop}
          pawnSlide={lastMove ? { from: lastMove.from, to: lastMove.to } : undefined}
          readOnly
          arrows={currentArrows}
        />

        {/* White player (bottom) */}
        <div className="flex items-center gap-2 mt-1 px-1">
          <div className="w-3 h-3 rounded-full bg-white border border-foreground/30" />
          <span className="text-sm text-muted">{game.white}</span>
        </div>

        {/* Navigation controls */}
        <div className="flex items-center justify-center gap-2 mt-3">
          <NavButton onClick={() => setCurrentMove(0)} disabled={currentMove === 0} label="Start">
            ⏮
          </NavButton>
          <NavButton onClick={goBack} disabled={currentMove === 0} label="Back">
            ◀
          </NavButton>
          <NavButton
            onClick={() => setIsPlaying(p => !p)}
            disabled={false}
            label={isPlaying ? "Pause" : "Play"}
            wide
          >
            {isPlaying ? "⏸" : "▶"}
          </NavButton>
          <NavButton onClick={goForward} disabled={currentMove >= totalMoves} label="Forward">
            ▶
          </NavButton>
          <NavButton
            onClick={() => setCurrentMove(totalMoves)}
            disabled={currentMove >= totalMoves}
            label="End"
          >
            ⏭
          </NavButton>
        </div>

        {/* Test button */}
        <div className="flex justify-center mt-3">
          <button
            onClick={startTestMode}
            className="px-5 py-2 rounded-lg border border-card-border bg-card hover:bg-btn-hover transition-colors text-sm font-medium"
          >
            Test Yourself
          </button>
        </div>

        {/* Move comment */}
        <div className="mt-3 min-h-12">
          {currentComment && (
            <p className="text-sm text-muted italic text-center px-2">
              {currentComment}
            </p>
          )}
        </div>
      </div>

      {/* Move list side */}
      <div className="lg:w-56 w-full">
        <div className="text-sm mb-2">
          <span className="font-bold">{game.event}</span>
          <span className="text-faint ml-2">{game.year}</span>
        </div>
        <p className="text-xs text-muted mb-3">{game.description}</p>

        <div
          ref={moveListRef}
          className="rounded-lg border border-card-border bg-card p-3 max-h-[400px] overflow-y-auto"
        >
          <div className="grid grid-cols-[2rem_1fr_1fr] gap-x-1 gap-y-0.5 text-sm">
            {movePairs.map((pair, i) => (
              <MoveRow
                key={i}
                num={pair.num}
                white={pair.white}
                black={pair.black}
                whiteActive={currentMove === i * 2 + 1}
                blackActive={currentMove === i * 2 + 2}
                onClickWhite={() => setCurrentMove(i * 2 + 1)}
                onClickBlack={() => setCurrentMove(i * 2 + 2)}
              />
            ))}
          </div>
          {game.result && (
            <div className="text-center text-sm font-bold text-muted mt-2">{game.result}</div>
          )}
        </div>
      </div>
    </div>
  );
}

function MoveRow({
  num,
  white,
  black,
  whiteActive,
  blackActive,
  onClickWhite,
  onClickBlack,
}: {
  num: number;
  white: string;
  black?: string;
  whiteActive: boolean;
  blackActive: boolean;
  onClickWhite: () => void;
  onClickBlack: () => void;
}) {
  return (
    <>
      <span className="text-faint text-right">{num}.</span>
      <button
        data-active={whiteActive}
        onClick={onClickWhite}
        className={`text-left px-1.5 py-0.5 rounded cursor-pointer transition-colors ${
          whiteActive
            ? "bg-btn-hover font-bold"
            : "hover:bg-btn"
        }`}
      >
        {white}
      </button>
      {black ? (
        <button
          data-active={blackActive}
          onClick={onClickBlack}
          className={`text-left px-1.5 py-0.5 rounded cursor-pointer transition-colors ${
            blackActive
              ? "bg-btn-hover font-bold"
              : "hover:bg-btn"
          }`}
        >
          {black}
        </button>
      ) : (
        <span />
      )}
    </>
  );
}

function NavButton({
  onClick,
  disabled,
  label,
  wide,
  children,
}: {
  onClick: () => void;
  disabled: boolean;
  label: string;
  wide?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      aria-label={label}
      className={`${
        wide ? "px-6" : "px-3"
      } py-2 rounded-lg bg-btn hover:bg-btn-hover disabled:opacity-30 disabled:cursor-not-allowed transition-colors text-lg`}
    >
      {children}
    </button>
  );
}

// src/lib/components/game/GameViewer.svelte
<script lang="ts">
  import Board from '$lib/components/board/Board.svelte';
  import { parseGamePgn, extractMainLine } from '$lib/logic/pgn';
  import { getLegalMoves } from '$lib/logic/attacks';
  import { playSound } from '$lib/state/sound';
  import type { ModelGame } from '$lib/games/types';
  import type { SquareId, PieceColor } from '$lib/logic/types';
  import type { Arrow, GameNode } from '$lib/logic/pgn';

  const AUTOPLAY_MS = 1200;

  let { game }: { game: ModelGame } = $props();

  let tree = $derived(parseGamePgn(game.pgn));
  let flatParsed = $derived(extractMainLine(tree));
  let totalMoves = $derived(flatParsed.moves.length);

  // === Viewer state — path-based navigation ===
  let currentPath = $state<GameNode[]>([]);
  let isPlaying = $state(false);
  let pauseOnVariations = $state(false);

  // Current position derived from path
  let board = $derived(
    currentPath.length > 0
      ? currentPath[currentPath.length - 1].boardAfter
      : tree.startBoard
  );

  let lastNode = $derived(
    currentPath.length > 0 ? currentPath[currentPath.length - 1] : null
  );
  let currentComment = $derived(
    currentPath.length === 0 ? tree.comment : lastNode?.comment
  );
  let currentArrows = $derived(lastNode?.arrows);
  let lastMoveSlide = $derived(
    lastNode ? { from: lastNode.from, to: lastNode.to } : undefined
  );

  // === Test mode state ===
  let testMode = $state(false);
  let testMoveIdx = $state(0);
  let testSelected = $state<SquareId | null>(null);
  let testHintArrow = $state<Arrow | null>(null);
  let testComplete = $state(false);
  let testDragFrom = $state<SquareId | null>(null);

  let moveListEl = $state<HTMLDivElement | undefined>(undefined);

  let testBoard = $derived(testMode ? flatParsed.positions[testMoveIdx] : board);
  let testColorToMove: PieceColor = $derived(testMoveIdx % 2 === 0 ? 'w' : 'b');

  let testValidMoves = $derived.by(() => {
    if (!testMode || !testSelected || testComplete) return [];
    return getLegalMoves(testSelected, flatParsed.positions[testMoveIdx], testColorToMove);
  });

  let testDragMoves = $derived.by(() => {
    if (!testMode || !testDragFrom || testComplete) return [];
    return getLegalMoves(testDragFrom, flatParsed.positions[testMoveIdx], testColorToMove);
  });

  let testStatusText = $derived.by(() => {
    if (testComplete) return 'You did it! You reproduced the entire game.';
    const moveNum = Math.floor(testMoveIdx / 2) + 1;
    const isWhiteTurn = testMoveIdx % 2 === 0;
    return `Move ${moveNum}${isWhiteTurn ? '.' : '...'} ${isWhiteTurn ? 'White' : 'Black'} to play`;
  });

  let testArrows = $derived(testHintArrow ? [testHintArrow] : undefined);

  // === Navigation ===
  function goForward() {
    const parent = currentPath.length > 0 ? currentPath[currentPath.length - 1] : null;
    const children = parent ? parent.children : tree.children;
    if (children.length > 0) {
      currentPath = [...currentPath, children[0]];
    }
  }

  function goBack() {
    if (currentPath.length > 0) {
      currentPath = currentPath.slice(0, -1);
    }
  }

  function goToStart() {
    currentPath = [];
  }

  function goToEnd() {
    let path = [...currentPath];
    let node = path.length > 0 ? path[path.length - 1] : null;
    let children = node ? node.children : tree.children;
    while (children.length > 0) {
      path.push(children[0]);
      children = children[0].children;
    }
    currentPath = path;
  }

  function goToNode(path: GameNode[]) {
    currentPath = path;
  }

  function togglePlay() {
    isPlaying = !isPlaying;
  }

  let canGoForward = $derived.by(() => {
    const parent = currentPath.length > 0 ? currentPath[currentPath.length - 1] : null;
    const children = parent ? parent.children : tree.children;
    return children.length > 0;
  });

  // === Auto-play ===
  $effect(() => {
    if (testMode) return;
    if (!isPlaying || !canGoForward) {
      if (!canGoForward) isPlaying = false;
      return;
    }
    // Check if we should pause at variations
    if (pauseOnVariations) {
      const parent = currentPath.length > 0 ? currentPath[currentPath.length - 1] : null;
      const children = parent ? parent.children : tree.children;
      if (children.length > 1) {
        isPlaying = false;
        return;
      }
    }
    const timer = setTimeout(() => {
      goForward();
    }, AUTOPLAY_MS);
    return () => clearTimeout(timer);
  });

  // === Keyboard controls ===
  function handleKeydown(e: KeyboardEvent) {
    if (testMode) return;
    if (e.key === 'ArrowLeft') { e.preventDefault(); goBack(); }
    else if (e.key === 'ArrowRight') { e.preventDefault(); goForward(); }
    else if (e.key === ' ') { e.preventDefault(); togglePlay(); }
  }

  // === Scroll current move into view ===
  $effect(() => {
    if (testMode) return;
    void currentPath;
    if (!moveListEl) return;
    const highlighted = moveListEl.querySelector("[data-active='true']") as HTMLElement | null;
    if (!highlighted) return;
    const top = highlighted.offsetTop - moveListEl.offsetTop;
    const bottom = top + highlighted.offsetHeight;
    if (top < moveListEl.scrollTop) {
      moveListEl.scrollTop = top;
    } else if (bottom > moveListEl.scrollTop + moveListEl.clientHeight) {
      moveListEl.scrollTop = bottom - moveListEl.clientHeight;
    }
  });

  // === Move list rendering ===
  // We need a structure that can render main line in the grid and variations inline.
  interface MoveListItem {
    kind: 'move';
    node: GameNode;
    path: GameNode[];
    moveNumber: number;
    isWhite: boolean;
  }

  interface VariationItem {
    kind: 'variation';
    nodes: { node: GameNode; path: GameNode[]; moveNumber: number; isWhite: boolean }[];
  }

  type ListItem = MoveListItem | VariationItem;

  let moveListItems = $derived.by(() => {
    const items: ListItem[] = [];
    buildMoveList(tree.children, [], 1, true, items, false);
    return items;
  });

  function buildMoveList(
    children: GameNode[],
    parentPath: GameNode[],
    moveNumber: number,
    isWhite: boolean,
    items: ListItem[],
    _isVariation: boolean,
  ) {
    if (children.length === 0) return;

    const mainChild = children[0];
    const mainPath = [...parentPath, mainChild];

    items.push({
      kind: 'move',
      node: mainChild,
      path: mainPath,
      moveNumber,
      isWhite,
    });

    // Variations (children[1+])
    for (let v = 1; v < children.length; v++) {
      const varNodes: VariationItem['nodes'] = [];
      let varNode: GameNode | undefined = children[v];
      let varPath = [...parentPath];
      let varMoveNum = moveNumber;
      let varIsWhite = isWhite;

      while (varNode) {
        varPath = [...varPath, varNode];
        varNodes.push({
          node: varNode,
          path: [...varPath],
          moveNumber: varMoveNum,
          isWhite: varIsWhite,
        });
        if (!varIsWhite) varMoveNum++;
        varIsWhite = !varIsWhite;
        varNode = varNode.children[0];
      }

      items.push({ kind: 'variation', nodes: varNodes });
    }

    // Continue main line
    const nextMoveNum = isWhite ? moveNumber : moveNumber + 1;
    buildMoveList(mainChild.children, mainPath, nextMoveNum, !isWhite, items, _isVariation);
  }

  // Check if a node path matches currentPath
  function isActivePath(path: GameNode[]): boolean {
    if (path.length !== currentPath.length) return false;
    for (let i = 0; i < path.length; i++) {
      if (path[i] !== currentPath[i]) return false;
    }
    return true;
  }

  // Check if a path is "on" the current path (current path passes through it)
  function isOnCurrentPath(path: GameNode[]): boolean {
    if (path.length > currentPath.length) return false;
    for (let i = 0; i < path.length; i++) {
      if (path[i] !== currentPath[i]) return false;
    }
    return true;
  }

  // Build move pairs for grid rendering from the main line items
  interface MovePair {
    num: number;
    white: { node: GameNode; path: GameNode[] } | null;
    black: { node: GameNode; path: GameNode[] } | null;
    variationsAfterWhite: VariationItem[];
    variationsAfterBlack: VariationItem[];
  }

  let movePairs = $derived.by(() => {
    const pairs: MovePair[] = [];
    let currentPair: MovePair | null = null;
    const pendingVariations: VariationItem[] = [];

    for (const item of moveListItems) {
      if (item.kind === 'variation') {
        pendingVariations.push(item);
        continue;
      }

      if (item.isWhite) {
        // Flush pending variations to previous pair's black
        if (pendingVariations.length > 0 && currentPair) {
          currentPair.variationsAfterBlack.push(...pendingVariations.splice(0));
        }
        currentPair = {
          num: item.moveNumber,
          white: { node: item.node, path: item.path },
          black: null,
          variationsAfterWhite: [],
          variationsAfterBlack: [],
        };
        pairs.push(currentPair);
        // Flush pending variations (e.g., from interrupted black move in a prior variation)
        if (pendingVariations.length > 0) {
          // These would be variations after the previous move
          // Actually they should go to the previous pair
          const prevPair = pairs.length >= 2 ? pairs[pairs.length - 2] : null;
          if (prevPair) {
            prevPair.variationsAfterBlack.push(...pendingVariations.splice(0));
          } else {
            pendingVariations.length = 0;
          }
        }
      } else {
        if (!currentPair) {
          // Black move without a white move (shouldn't happen in normal games, but handle it)
          currentPair = {
            num: item.moveNumber,
            white: null,
            black: { node: item.node, path: item.path },
            variationsAfterWhite: [],
            variationsAfterBlack: [],
          };
          pairs.push(currentPair);
        } else {
          // Flush pending variations to after white
          if (pendingVariations.length > 0) {
            currentPair.variationsAfterWhite.push(...pendingVariations.splice(0));
          }
          currentPair.black = { node: item.node, path: item.path };
        }
      }
    }

    // Flush remaining variations
    if (pendingVariations.length > 0 && currentPair) {
      if (currentPair.black) {
        currentPair.variationsAfterBlack.push(...pendingVariations.splice(0));
      } else {
        currentPair.variationsAfterWhite.push(...pendingVariations.splice(0));
      }
    }

    return pairs;
  });

  // === Test mode logic ===
  function advanceTestMove(from: SquareId, to: SquareId) {
    const expected = flatParsed.moves[testMoveIdx];
    if (from === expected.from && to === expected.to) {
      testHintArrow = null;
      const next = testMoveIdx + 1;
      if (next >= totalMoves) {
        testMoveIdx = next;
        testComplete = true;
        playSound('stars');
      } else {
        testMoveIdx = next;
      }
      testSelected = null;
      playSound('move');
    } else {
      testHintArrow = { from: expected.from, to: expected.to, color: '#15803d' };
      testSelected = null;
      playSound('wrong');
    }
  }

  function handleTestClick(sq: SquareId) {
    if (testComplete) return;
    const currentBoard = flatParsed.positions[testMoveIdx];

    if (!testSelected) {
      const p = currentBoard.pieces.get(sq);
      if (p && p.color === testColorToMove) {
        testSelected = sq;
        testHintArrow = null;
      }
      return;
    }

    if (sq === testSelected) {
      testSelected = null;
      return;
    }

    const target = currentBoard.pieces.get(sq);
    if (target && target.color === testColorToMove) {
      testSelected = sq;
      return;
    }

    const legal = getLegalMoves(testSelected, currentBoard, testColorToMove);
    if (!legal.includes(sq)) {
      testSelected = null;
      return;
    }

    advanceTestMove(testSelected, sq);
  }

  function handleTestDrop(from: SquareId, to: SquareId) {
    if (testComplete || from === to) return;
    const currentBoard = flatParsed.positions[testMoveIdx];
    const p = currentBoard.pieces.get(from);
    if (!p || p.color !== testColorToMove) return;
    const legal = getLegalMoves(from, currentBoard, testColorToMove);
    if (!legal.includes(to)) return;
    advanceTestMove(from, to);
  }

  function handleTestDragStart(sq: SquareId) {
    if (testComplete) return;
    testDragFrom = sq;
    testHintArrow = null;
  }

  function handleTestDragEnd() {
    testDragFrom = null;
  }

  function startTestMode() {
    testMode = true;
    testMoveIdx = 0;
    testSelected = null;
    testHintArrow = null;
    testComplete = false;
    isPlaying = false;
  }

  function exitTestMode() {
    testMode = false;
    testSelected = null;
    testHintArrow = null;
    testComplete = false;
    currentPath = [];
  }

  function retryTest() {
    testMoveIdx = 0;
    testComplete = false;
    testHintArrow = null;
  }

  function noop() {}

  function formatVariationSan(node: { node: GameNode; moveNumber: number; isWhite: boolean }): string {
    const prefix = node.isWhite ? `${node.moveNumber}.` : (node === node ? `${node.moveNumber}...` : '');
    return `${prefix}${node.node.san}${node.node.nag ?? ''}`;
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if testMode}
  <div class="test-wrapper">
    <div class="test-header">
      <h2 class="test-title">Test Mode</h2>
      <p class="test-status">{testStatusText}</p>
    </div>

    <div class="board-container">
      <div class="player-label">
        <div class="player-dot player-dot-black"></div>
        <span class="player-name">{game.black}</span>
      </div>

      <Board
        board={testBoard}
        selectedSquare={testSelected}
        validMoves={testValidMoves}
        targets={[]}
        reachedTargets={[]}
        dragValidMoves={testDragMoves}
        onSquareClick={handleTestClick}
        onDrop={handleTestDrop}
        onDragStart={handleTestDragStart}
        onDragEnd={handleTestDragEnd}
        playableColors={['w', 'b']}
        arrows={testArrows}
      />

      <div class="player-label">
        <div class="player-dot player-dot-white"></div>
        <span class="player-name">{game.white}</span>
      </div>
    </div>

    <div class="test-buttons">
      {#if testComplete}
        <button class="btn-try-again" onclick={retryTest}>
          Try Again
        </button>
      {/if}
      <button class="btn-back-viewer" onclick={exitTestMode}>
        Back to Viewer
      </button>
    </div>
  </div>
{:else}
  <div class="viewer-layout">
    <div class="board-side">
      <div class="player-label">
        <div class="player-dot player-dot-black"></div>
        <span class="player-name">{game.black}</span>
      </div>

      <Board
        board={board}
        selectedSquare={null}
        validMoves={[]}
        targets={[]}
        reachedTargets={[]}
        dragValidMoves={[]}
        onSquareClick={noop}
        onDrop={noop}
        onDragStart={noop}
        onDragEnd={noop}
        pawnSlide={lastMoveSlide}
        readOnly={true}
        arrows={currentArrows}
      />

      <div class="player-label">
        <div class="player-dot player-dot-white"></div>
        <span class="player-name">{game.white}</span>
      </div>

      <div class="nav-controls">
        <button
          class="nav-btn"
          onclick={goToStart}
          disabled={currentPath.length === 0}
          aria-label="Start"
        >&#x23EE;</button>
        <button
          class="nav-btn"
          onclick={goBack}
          disabled={currentPath.length === 0}
          aria-label="Back"
        >&#x25C0;</button>
        <button
          class="nav-btn nav-btn-wide"
          onclick={togglePlay}
          aria-label={isPlaying ? 'Pause' : 'Play'}
        >{isPlaying ? '\u23F8' : '\u25B6'}</button>
        <button
          class="nav-btn"
          onclick={goForward}
          disabled={!canGoForward}
          aria-label="Forward"
        >&#x25B6;</button>
        <button
          class="nav-btn"
          onclick={goToEnd}
          disabled={!canGoForward}
          aria-label="End"
        >&#x23ED;</button>
      </div>

      <div class="sub-controls">
        <label class="variation-toggle">
          <input type="checkbox" bind:checked={pauseOnVariations} />
          Pause at variations
        </label>
      </div>

      <div class="test-btn-wrap">
        <button class="btn-test" onclick={startTestMode}>
          Test Yourself
        </button>
      </div>

      <div class="comment-area">
        {#if currentComment}
          <p class="comment-text">{currentComment}</p>
        {/if}
      </div>
    </div>

    <div class="move-list-side">
      <div class="game-info">
        <span class="game-event">{game.event}</span>
        <span class="game-year">{game.year}</span>
      </div>
      <p class="game-desc">{game.description}</p>

      <div class="move-list" bind:this={moveListEl}>
        <div class="move-grid">
          {#each movePairs as pair}
            <span class="move-num">{pair.num}.</span>
            {#if pair.white}
              <button
                class={['move-btn', isActivePath(pair.white.path) && 'move-active', isOnCurrentPath(pair.white.path) && !isActivePath(pair.white.path) && 'move-on-path']}
                data-active={isActivePath(pair.white.path)}
                onclick={() => goToNode(pair.white!.path)}
              >
                {pair.white.node.san}{pair.white.node.nag ?? ''}
              </button>
            {:else}
              <span></span>
            {/if}

            {#if pair.variationsAfterWhite.length > 0}
              {#if !pair.black}
                <span></span>
              {/if}
              {#each pair.variationsAfterWhite as variation}
                <span class="variation-row">({#each variation.nodes as vn, vi}{#if vi > 0}{' '}{/if}<button
                  class={['var-move-btn', isActivePath(vn.path) && 'move-active']}
                  data-active={isActivePath(vn.path)}
                  onclick={() => goToNode(vn.path)}
                >{formatVariationSan(vn)}</button>{/each})</span>
              {/each}
            {/if}

            {#if pair.black}
              {#if pair.variationsAfterWhite.length > 0}
                <span class="move-num">{pair.num}.</span>
                <span class="move-ellipsis">...</span>
              {/if}
              <button
                class={['move-btn', isActivePath(pair.black.path) && 'move-active', isOnCurrentPath(pair.black.path) && !isActivePath(pair.black.path) && 'move-on-path']}
                data-active={isActivePath(pair.black.path)}
                onclick={() => goToNode(pair.black!.path)}
              >
                {pair.black.node.san}{pair.black.node.nag ?? ''}
              </button>
            {:else if pair.variationsAfterWhite.length === 0}
              <span></span>
            {/if}

            {#if pair.variationsAfterBlack.length > 0}
              {#each pair.variationsAfterBlack as variation}
                <span class="variation-row">({#each variation.nodes as vn, vi}{#if vi > 0}{' '}{/if}<button
                  class={['var-move-btn', isActivePath(vn.path) && 'move-active']}
                  data-active={isActivePath(vn.path)}
                  onclick={() => goToNode(vn.path)}
                >{formatVariationSan(vn)}</button>{/each})</span>
              {/each}
            {/if}
          {/each}
        </div>
        {#if game.result}
          <div class="game-result">{game.result}</div>
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  /* --- Test Mode --- */
  .test-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    max-width: 56rem;
    margin: 0 auto;
  }

  .test-header {
    text-align: center;
  }

  .test-title {
    font-size: 1.25rem;
    font-weight: 700;
    margin: 0 0 0.25rem;
  }

  .test-status {
    color: var(--text-muted, #888);
    margin: 0;
  }

  .test-buttons {
    display: flex;
    gap: 0.75rem;
  }

  .btn-try-again {
    padding: 0.5rem 1.25rem;
    background: #16a34a;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.15s;
  }

  .btn-try-again:hover {
    background: #15803d;
  }

  .btn-back-viewer {
    padding: 0.5rem 1.25rem;
    border-radius: 0.5rem;
    border: 1px solid var(--card-border, #333);
    background: var(--card-bg, #1a1a1a);
    color: inherit;
    cursor: pointer;
    transition: background-color 0.15s;
  }

  .btn-back-viewer:hover {
    background: var(--btn-hover, #2a2a2a);
  }

  /* --- Player labels --- */
  .player-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.25rem;
  }

  .player-dot {
    width: 0.75rem;
    height: 0.75rem;
    border-radius: 50%;
    border: 1px solid rgba(255, 255, 255, 0.3);
  }

  .player-dot-black {
    background: #1a1a1a;
  }

  .player-dot-white {
    background: white;
  }

  .player-name {
    font-size: 0.875rem;
    color: var(--text-muted, #888);
  }

  /* --- Board container (shared test/viewer) --- */
  .board-container {
    width: 100%;
    max-width: 560px;
  }

  /* --- Viewer layout --- */
  .viewer-layout {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
    align-items: flex-start;
    max-width: 56rem;
    margin: 0 auto;
  }

  @media (min-width: 1024px) {
    .viewer-layout {
      flex-direction: row;
    }
  }

  .board-side {
    flex: 1;
    width: 100%;
    max-width: 560px;
  }

  @media (min-width: 1024px) {
    .board-side {
      max-width: 560px;
    }
  }

  /* --- Nav controls --- */
  .nav-controls {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    margin-top: 0.75rem;
  }

  .nav-btn {
    padding: 0.5rem 0.75rem;
    border-radius: 0.5rem;
    background: var(--btn-bg, #2a2a2a);
    color: inherit;
    border: none;
    cursor: pointer;
    font-size: 1.125rem;
    transition: background-color 0.15s;
  }

  .nav-btn:hover:not(:disabled) {
    background: var(--btn-hover, #3a3a3a);
  }

  .nav-btn:disabled {
    opacity: 0.3;
    cursor: not-allowed;
  }

  .nav-btn-wide {
    padding-left: 1.5rem;
    padding-right: 1.5rem;
  }

  /* --- Sub controls --- */
  .sub-controls {
    display: flex;
    justify-content: center;
    margin-top: 0.5rem;
  }

  .variation-toggle {
    font-size: 0.75rem;
    color: var(--text-faint, #666);
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 0.375rem;
  }

  .variation-toggle input {
    cursor: pointer;
  }

  /* --- Test yourself button --- */
  .test-btn-wrap {
    display: flex;
    justify-content: center;
    margin-top: 0.75rem;
  }

  .btn-test {
    padding: 0.5rem 1.25rem;
    border-radius: 0.5rem;
    border: 1px solid var(--card-border, #333);
    background: var(--card-bg, #1a1a1a);
    color: inherit;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.15s;
  }

  .btn-test:hover {
    background: var(--btn-hover, #2a2a2a);
  }

  /* --- Comment area --- */
  .comment-area {
    margin-top: 0.75rem;
    min-height: 3rem;
  }

  .comment-text {
    font-size: 0.875rem;
    color: var(--text-muted, #888);
    font-style: italic;
    text-align: center;
    padding: 0 0.5rem;
    margin: 0;
  }

  /* --- Move list side --- */
  .move-list-side {
    width: 100%;
  }

  @media (min-width: 1024px) {
    .move-list-side {
      width: 14rem;
    }
  }

  .game-info {
    font-size: 0.875rem;
    margin-bottom: 0.5rem;
  }

  .game-event {
    font-weight: 700;
  }

  .game-year {
    color: var(--text-faint, #666);
    margin-left: 0.5rem;
  }

  .game-desc {
    font-size: 0.75rem;
    color: var(--text-muted, #888);
    margin: 0 0 0.75rem;
  }

  .move-list {
    border-radius: 0.5rem;
    border: 1px solid var(--card-border, #333);
    background: var(--card-bg, #1a1a1a);
    padding: 0.75rem;
    max-height: 400px;
    overflow-y: auto;
  }

  .move-grid {
    display: grid;
    grid-template-columns: 2rem 1fr 1fr;
    column-gap: 0.25rem;
    row-gap: 0.125rem;
    font-size: 0.875rem;
  }

  .move-num {
    color: var(--text-faint, #666);
    text-align: right;
  }

  .move-btn {
    text-align: left;
    padding: 0.125rem 0.375rem;
    border-radius: 0.25rem;
    cursor: pointer;
    background: none;
    border: none;
    color: inherit;
    font-size: inherit;
    transition: background-color 0.15s;
  }

  .move-btn:hover {
    background: var(--btn-bg, #2a2a2a);
  }

  .move-active {
    background: var(--btn-hover, #3a3a3a);
    font-weight: 700;
  }

  .move-on-path {
    color: var(--foreground, #f0e6cc);
  }

  .move-ellipsis {
    color: var(--text-faint, #666);
    padding: 0.125rem 0.375rem;
  }

  .game-result {
    text-align: center;
    font-size: 0.875rem;
    font-weight: 700;
    color: var(--text-muted, #888);
    margin-top: 0.5rem;
  }

  /* --- Variation rows --- */
  .variation-row {
    grid-column: 1 / -1;
    font-size: 0.8rem;
    color: var(--text-muted, #888);
    padding: 0.125rem 0.25rem 0.125rem 2.25rem;
  }

  .var-move-btn {
    background: none;
    border: none;
    color: var(--text-muted, #888);
    cursor: pointer;
    font-size: inherit;
    padding: 0.0625rem 0.125rem;
    border-radius: 0.125rem;
    transition: background-color 0.15s;
  }

  .var-move-btn:hover {
    background: var(--btn-bg, #2a2a2a);
    color: inherit;
  }

  .var-move-btn.move-active {
    background: var(--btn-hover, #3a3a3a);
    color: inherit;
    font-weight: 700;
  }
</style>
