// src/components/board/CoordinateTrainer.tsx
"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import Link from "next/link";
import { FILES, RANKS, SquareId } from "@/lib/logic/types";
import StarRating from "@/components/puzzle/StarRating";

const SQUARE_SIZE = 100;
const BOARD_SIZE = SQUARE_SIZE * 8;
const LIGHT = "#d4c4a0";
const DARK = "#7a9e6e";
const CORRECT_COLOR = "#4ade80";
const WRONG_COLOR = "#ef4444";
const GAME_DURATION = 30;

const ALL_SQUARES: SquareId[] = [];
for (const f of FILES) {
  for (const r of RANKS) {
    ALL_SQUARES.push(`${f}${r}` as SquareId);
  }
}

function randomSquare(exclude?: SquareId): SquareId {
  let sq: SquareId;
  do {
    sq = ALL_SQUARES[Math.floor(Math.random() * 64)];
  } while (sq === exclude);
  return sq;
}

type GameState = "idle" | "playing" | "done";

function scoreToStars(score: number): number {
  if (score >= 10) return 3;
  if (score >= 5) return 2;
  if (score >= 3) return 1;
  return 0;
}

export default function CoordinateTrainer() {
  const [gameState, setGameState] = useState<GameState>("idle");
  const [target, setTarget] = useState<SquareId>(() => randomSquare());
  const [score, setScore] = useState(0);
  const [timeLeft, setTimeLeft] = useState(GAME_DURATION);
  const [flash, setFlash] = useState<{ sq: SquareId; correct: boolean } | null>(null);
  const [bestScore, setBestScore] = useState<number>(() => {
    if (typeof window === "undefined") return 0;
    return parseInt(localStorage.getItem("coord-best") ?? "0", 10);
  });
  const [bestStars, setBestStars] = useState<number>(() => {
    if (typeof window === "undefined") return 0;
    return parseInt(localStorage.getItem("coord-best-stars") ?? "0", 10);
  });
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const startGame = useCallback(() => {
    setGameState("playing");
    setScore(0);
    setTimeLeft(GAME_DURATION);
    setTarget(randomSquare());
    setFlash(null);
  }, []);

  // Countdown timer
  useEffect(() => {
    if (gameState !== "playing") return;
    timerRef.current = setInterval(() => {
      setTimeLeft((t) => {
        if (t <= 1) {
          clearInterval(timerRef.current!);
          setGameState("done");
          return 0;
        }
        return t - 1;
      });
    }, 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [gameState]);

  // Save best score and stars
  useEffect(() => {
    if (gameState !== "done") return;
    if (score > bestScore) {
      setBestScore(score);
      localStorage.setItem("coord-best", String(score));
    }
    const stars = scoreToStars(score);
    if (stars > bestStars) {
      setBestStars(stars);
      localStorage.setItem("coord-best-stars", String(stars));
    }
  }, [gameState, score, bestScore, bestStars]);

  const handleClick = useCallback(
    (sq: SquareId) => {
      if (gameState !== "playing") return;
      if (sq === target) {
        setScore((s) => s + 1);
        setFlash({ sq, correct: true });
        setTarget(randomSquare(sq));
      } else {
        setFlash({ sq, correct: false });
      }
      setTimeout(() => setFlash(null), 200);
    },
    [gameState, target],
  );

  const progressPct = (timeLeft / GAME_DURATION) * 100;

  return (
    <div className="flex flex-col items-center gap-4">
      {/* Pre-game / post-game messages */}
      {gameState === "idle" && (
        <div className="text-center">
          <p className="text-muted mb-4">
            A coordinate appears — click the right square. How many can you get in {GAME_DURATION} seconds?
          </p>
          <button
            onClick={startGame}
            className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold text-lg hover:bg-green-700 transition-colors"
          >
            Start
          </button>
        </div>
      )}
      {gameState === "done" && (
        <div className="text-center">
          <div className="mb-2"><StarRating stars={scoreToStars(score)} size="lg" /></div>
          <div className="text-4xl font-bold mb-1">{score}</div>
          <p className="text-muted mb-1">
            {score >= 20 ? "Amazing!" : score >= 15 ? "Great job!" : score >= 10 ? "Nice work!" : "Keep practicing!"}
          </p>
          {bestScore > 0 && (
            <p className="text-sm text-faint mb-1">Best: {bestScore}</p>
          )}
          <div className="flex justify-center gap-4 text-xs text-faint mb-3">
            <span><StarRating stars={3} size="sm" /> 10+</span>
            <span><StarRating stars={2} size="sm" /> 5+</span>
            <span><StarRating stars={1} size="sm" /> 3+</span>
          </div>
          <div className="flex justify-center gap-3">
            <button
              onClick={startGame}
              className="px-6 py-3 bg-btn hover:bg-btn-hover rounded-lg font-bold text-lg transition-colors"
            >
              Play Again
            </button>
            <Link
              href="/setup"
              className="px-6 py-3 bg-green-600 text-white rounded-lg font-bold text-lg hover:bg-green-700 transition-colors"
            >
              Place the Pieces!
            </Link>
          </div>
        </div>
      )}

      {/* Timer bar + score */}
      {gameState === "playing" && (
        <div className="w-full max-w-[min(90vw,90vh-8rem)] flex items-center gap-3">
          <span className="text-sm font-bold w-8 text-right">{timeLeft}s</span>
          <div className="flex-1 h-2 rounded-full bg-btn overflow-hidden">
            <div
              className="h-full rounded-full transition-all duration-1000 ease-linear"
              style={{
                width: `${progressPct}%`,
                backgroundColor: timeLeft <= 5 ? "#ef4444" : timeLeft <= 10 ? "#f59e0b" : "#4ade80",
              }}
            />
          </div>
          <span className="text-sm font-bold w-8">{score}</span>
        </div>
      )}

      {/* Board */}
      <svg
        viewBox={`0 0 ${BOARD_SIZE} ${BOARD_SIZE}`}
        className="w-full max-w-[min(90vw,90vh-8rem)] aspect-square touch-none"
      >
        {RANKS.map((rank, ri) =>
          FILES.map((file, fi) => {
            const sq = `${file}${rank}` as SquareId;
            const isLight = (fi + ri) % 2 === 0;
            const isFlash = flash && flash.sq === sq;

            let fill = isLight ? LIGHT : DARK;
            if (isFlash) {
              fill = flash.correct ? CORRECT_COLOR : WRONG_COLOR;
            }

            return (
              <g
                key={sq}
                onClick={() => handleClick(sq)}
                className={gameState === "playing" ? "cursor-pointer" : ""}
              >
                <rect
                  x={fi * SQUARE_SIZE}
                  y={ri * SQUARE_SIZE}
                  width={SQUARE_SIZE}
                  height={SQUARE_SIZE}
                  fill={fill}
                />
                {/* File labels on bottom rank */}
                {ri === 7 && (
                  <text
                    x={fi * SQUARE_SIZE + 5}
                    y={ri * SQUARE_SIZE + SQUARE_SIZE - 5}
                    fontSize="14"
                    fill={isLight ? DARK : LIGHT}
                    fontWeight="bold"
                    className="pointer-events-none select-none"
                  >
                    {file}
                  </text>
                )}
                {/* Rank labels on left file */}
                {fi === 0 && (
                  <text
                    x={5}
                    y={ri * SQUARE_SIZE + 16}
                    fontSize="14"
                    fill={isLight ? DARK : LIGHT}
                    fontWeight="bold"
                    className="pointer-events-none select-none"
                  >
                    {rank}
                  </text>
                )}
              </g>
            );
          }),
        )}

        {/* Target coordinate in center of board */}
        {gameState === "playing" && (
          <text
            x={BOARD_SIZE / 2}
            y={BOARD_SIZE / 2 + 36}
            fontSize="120"
            textAnchor="middle"
            fill="white"
            stroke="black"
            strokeWidth="3"
            paintOrder="stroke"
            fontWeight="bold"
            className="pointer-events-none select-none"
            style={{ filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.5))" }}
          >
            {target}
          </text>
        )}
      </svg>
    </div>
  );
}

// src/lib/components/board/CoordinateTrainer.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { FILES, RANKS, type SquareId } from '$lib/logic/types';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';

  const SQUARE_SIZE = 100;
  const BOARD_SIZE = SQUARE_SIZE * 8;
  const LIGHT = '#d4c4a0';
  const DARK = '#7a9e6e';
  const CORRECT_COLOR = '#4ade80';
  const WRONG_COLOR = '#ef4444';
  const GAME_DURATION = 30;

  const ALL_SQUARES: SquareId[] = [];
  for (const f of FILES) {
    for (const r of RANKS) {
      ALL_SQUARES.push(`${f}${r}` as SquareId);
    }
  }

  function randomSquare(exclude?: SquareId): SquareId {
    let sq: SquareId;
    do {
      sq = ALL_SQUARES[Math.floor(Math.random() * 64)];
    } while (sq === exclude);
    return sq;
  }

  function scoreToStars(score: number): number {
    if (score >= 10) return 3;
    if (score >= 5) return 2;
    if (score >= 3) return 1;
    return 0;
  }

  type GameState = 'idle' | 'playing' | 'done';

  let gameState = $state<GameState>('idle');
  let target = $state<SquareId>(randomSquare());
  let score = $state(0);
  let timeLeft = $state(GAME_DURATION);
  let flashSquare = $state<SquareId | null>(null);
  let flashColor = $state('');
  let bestScore = $state(0);
  let bestStars = $state(0);

  let timerRef: ReturnType<typeof setInterval> | null = null;
  let flashRef: ReturnType<typeof setTimeout> | null = null;

  onMount(() => {
    bestScore = parseInt(localStorage.getItem('coord-best') ?? '0', 10);
    bestStars = parseInt(localStorage.getItem('coord-best-stars') ?? '0', 10);

    return () => {
      if (timerRef) clearInterval(timerRef);
      if (flashRef) clearTimeout(flashRef);
    };
  });

  function startGame() {
    score = 0;
    timeLeft = GAME_DURATION;
    target = randomSquare();
    flashSquare = null;
    gameState = 'playing';

    if (timerRef) clearInterval(timerRef);
    timerRef = setInterval(() => {
      timeLeft -= 1;
      if (timeLeft <= 0) {
        endGame();
      }
    }, 1000);
  }

  function endGame() {
    if (timerRef) {
      clearInterval(timerRef);
      timerRef = null;
    }
    gameState = 'done';

    const stars = scoreToStars(score);
    if (score > bestScore) {
      bestScore = score;
      localStorage.setItem('coord-best', String(score));
    }
    if (stars > bestStars) {
      bestStars = stars;
      localStorage.setItem('coord-best-stars', String(stars));
    }
  }

  function handleSquareClick(sq: SquareId) {
    if (gameState !== 'playing') return;

    if (flashRef) clearTimeout(flashRef);

    if (sq === target) {
      flashSquare = sq;
      flashColor = CORRECT_COLOR;
      score += 1;
      target = randomSquare(target);
    } else {
      flashSquare = sq;
      flashColor = WRONG_COLOR;
    }

    flashRef = setTimeout(() => {
      flashSquare = null;
    }, 200);
  }

  function squareColor(fileIdx: number, rankIdx: number): string {
    return (fileIdx + rankIdx) % 2 === 0 ? LIGHT : DARK;
  }

  function timerBarColor(t: number): string {
    if (t > 20) return '#4ade80';
    if (t > 10) return '#facc15';
    return '#ef4444';
  }

  const DISPLAY_RANKS = ['8', '7', '6', '5', '4', '3', '2', '1'];
</script>

<div class="trainer">
  {#if gameState === 'idle'}
    <div class="start-screen">
      <p class="instructions">Click the correct square as fast as you can!</p>
      <div class="thresholds">
        <span class="threshold"><StarRating stars={1} size="sm" /> 3 correct</span>
        <span class="threshold"><StarRating stars={2} size="sm" /> 5 correct</span>
        <span class="threshold"><StarRating stars={3} size="sm" /> 10 correct</span>
      </div>
      {#if bestScore > 0}
        <p class="best">Best: {bestScore} <StarRating stars={bestStars} size="sm" /></p>
      {/if}
      <button class="start-btn" onclick={startGame}>Start</button>
    </div>
  {:else if gameState === 'playing'}
    <div class="hud">
      <div class="score">Score: {score}</div>
      <div class="timer">{timeLeft}s</div>
    </div>
    <div class="timer-bar-track">
      <div
        class="timer-bar-fill"
        style="width: {(timeLeft / GAME_DURATION) * 100}%; background: {timerBarColor(timeLeft)};"
      ></div>
    </div>
  {:else}
    <div class="done-screen">
      <div class="final-score">{score}</div>
      <StarRating stars={scoreToStars(score)} size="lg" />
      <div class="thresholds done-thresholds">
        <span class={['threshold', score >= 3 && 'achieved']}><StarRating stars={1} size="sm" /> 3</span>
        <span class={['threshold', score >= 5 && 'achieved']}><StarRating stars={2} size="sm" /> 5</span>
        <span class={['threshold', score >= 10 && 'achieved']}><StarRating stars={3} size="sm" /> 10</span>
      </div>
      {#if bestScore > 0}
        <p class="best">Best: {bestScore} <StarRating stars={bestStars} size="sm" /></p>
      {/if}
      <button class="start-btn" onclick={startGame}>Play Again</button>
      <a href="/setup" class="setup-link">Place the Pieces! &rarr;</a>
    </div>
  {/if}

  <div class="board-wrapper">
    <svg
      viewBox="0 0 {BOARD_SIZE} {BOARD_SIZE}"
      class="board-svg"
      xmlns="http://www.w3.org/2000/svg"
      role="application"
      aria-label="Chess board"
      tabindex="-1"
    >
      {#each FILES as file, fi}
        {#each DISPLAY_RANKS as rank, ri}
          {@const sq = `${file}${rank}` as SquareId}
          {@const x = fi * SQUARE_SIZE}
          {@const y = ri * SQUARE_SIZE}
          {@const fill =
            flashSquare === sq ? flashColor : squareColor(fi, ri)}
          <rect
            {x}
            {y}
            width={SQUARE_SIZE}
            height={SQUARE_SIZE}
            {fill}
            onclick={() => handleSquareClick(sq)}
            onkeydown={() => {}}
            role="button"
            tabindex="-1"
            aria-label={sq}
            style="cursor: {gameState === 'playing' ? 'pointer' : 'default'}"
          />
        {/each}
      {/each}

      <!-- File labels (a-h along bottom) -->
      {#each FILES as file, fi}
        <text
          x={fi * SQUARE_SIZE + SQUARE_SIZE / 2}
          y={BOARD_SIZE - 6}
          text-anchor="middle"
          font-size="14"
          font-weight="bold"
          fill={fi % 2 === 0 ? DARK : LIGHT}
          class="label"
        >{file}</text>
      {/each}

      <!-- Rank labels (1-8 along left) -->
      {#each DISPLAY_RANKS as rank, ri}
        <text
          x={6}
          y={ri * SQUARE_SIZE + 16}
          font-size="14"
          font-weight="bold"
          fill={ri % 2 === 0 ? DARK : LIGHT}
          class="label"
        >{rank}</text>
      {/each}

      <!-- Big coordinate text in center -->
      {#if gameState === 'playing'}
        <text
          x={BOARD_SIZE / 2}
          y={BOARD_SIZE / 2}
          text-anchor="middle"
          dominant-baseline="central"
          font-size="160"
          font-weight="bold"
          fill="white"
          opacity="0.85"
          class="label"
        >{target}</text>
      {/if}
    </svg>
  </div>
</div>

<style>
  .trainer {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .board-wrapper {
    width: 100%;
    max-width: min(90vw, calc(90vh - 8rem));
    aspect-ratio: 1;
    touch-action: none;
  }

  .board-svg {
    width: 100%;
    height: 100%;
    display: block;
    border-radius: 4px;
  }

  .label {
    pointer-events: none;
    user-select: none;
  }

  /* HUD */
  .hud {
    display: flex;
    justify-content: space-between;
    width: 100%;
    max-width: min(90vw, calc(90vh - 8rem));
    font-size: 1.25rem;
    font-weight: bold;
  }

  .timer-bar-track {
    width: 100%;
    max-width: min(90vw, calc(90vh - 8rem));
    height: 8px;
    background: rgba(255, 255, 255, 0.15);
    border-radius: 4px;
    overflow: hidden;
  }

  .timer-bar-fill {
    height: 100%;
    border-radius: 4px;
    transition: width 1s linear, background 0.5s;
  }

  /* Start / Done screens */
  .start-screen,
  .done-screen {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
  }

  .instructions {
    color: var(--text-muted);
    font-size: 1rem;
  }

  .thresholds {
    display: flex;
    gap: 1.25rem;
    font-size: 0.875rem;
    color: var(--text-faint);
  }

  .threshold {
    display: flex;
    align-items: center;
    gap: 0.25rem;
  }

  .done-thresholds .threshold {
    opacity: 0.4;
  }

  .done-thresholds .threshold.achieved {
    opacity: 1;
    color: var(--foreground);
  }

  .best {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .final-score {
    font-size: 3rem;
    font-weight: bold;
  }

  .start-btn {
    padding: 0.75rem 2.5rem;
    font-size: 1.125rem;
    font-weight: bold;
    border: none;
    border-radius: 0.5rem;
    background: rgba(255, 248, 230, 0.15);
    color: var(--foreground);
    cursor: pointer;
    transition: background 0.15s;
  }

  .start-btn:hover {
    background: rgba(255, 248, 230, 0.25);
  }

  .setup-link {
    font-size: 0.875rem;
    color: var(--text-muted);
    margin-top: 0.25rem;
  }

  .setup-link:hover {
    color: var(--foreground);
  }

  .score {
    color: var(--foreground);
  }

  .timer {
    color: var(--foreground);
  }
</style>
