// src/routes/openings/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { getOpening } from '$lib/openings';
  import OpeningTrainer from '$lib/components/opening/OpeningTrainer.svelte';

  let id = $derived(page.params.id);
  let opening = $derived(getOpening(id));
</script>

{#if opening}
  <main class="page">
    <a href="/openings" class="back-link">&larr; Back to openings</a>
    {#key opening.id}
      <OpeningTrainer {opening} />
    {/key}
  </main>
{:else}
  <main class="page center">
    <h1>Opening not found</h1>
    <a href="/openings" class="muted-link">Back to openings</a>
  </main>
{/if}

<style>
  .page {
    min-height: 100vh;
    padding: 1.5rem;
    max-width: 42rem;
    margin: 0 auto;
  }

  .center {
    text-align: center;
  }

  .back-link {
    font-size: 0.875rem;
    color: var(--text-muted);
    display: inline-block;
    margin-bottom: 1rem;
  }

  .back-link:hover {
    color: var(--foreground);
  }

  .muted-link {
    color: var(--text-muted);
  }

  .muted-link:hover {
    text-decoration: underline;
  }
</style>

// src/app/openings/[id]/page.tsx
"use client";

import { use } from "react";
import Link from "next/link";
import OpeningTrainer from "@/components/opening/OpeningTrainer";
import { getOpening } from "@/lib/openings";

export default function OpeningPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const opening = getOpening(id);

  if (!opening) {
    return (
      <main className="min-h-screen p-6 max-w-4xl mx-auto text-center">
        <h1 className="text-2xl font-bold mb-4">Not found</h1>
        <Link href="/openings" className="text-muted hover:underline">Back to openings</Link>
      </main>
    );
  }

  return (
    <main className="min-h-screen p-6">
      <div className="max-w-2xl mx-auto">
        <Link href="/openings" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
          &larr; Back to openings
        </Link>
      </div>
      <OpeningTrainer opening={opening} />
    </main>
  );
}
