// src/components/endgame/MateTrainer.tsx
"use client";

import { useState, useCallback, useMemo, useEffect } from "react";
import Board from "@/components/board/Board";
import StarRating from "@/components/puzzle/StarRating";
import { BoardState, SquareId, createBoardState } from "@/lib/logic/types";
import { getLegalMoves } from "@/lib/logic/attacks";
import {
  MateEndgameType,
  ENDGAME_INFO,
  generatePosition,
  validateEndgameMove,
  applyEndgameMove,
  pickDefenseMove,
} from "@/lib/logic/endgame";
import type { SlideAnimation } from "@/lib/state/use-puzzle";

interface MateTrainerProps {
  type: MateEndgameType;
}

export default function MateTrainer({ type }: MateTrainerProps) {
  const info = ENDGAME_INFO[type];
  const storageKey = `endings-${type}-best-stars`;

  const [board, setBoard] = useState<BoardState>(() =>
    createBoardState(generatePosition(type)),
  );
  const [selectedSquare, setSelectedSquare] = useState<SquareId | null>(null);
  const [result, setResult] = useState<"playing" | "won">("playing");
  const [mistakes, setMistakes] = useState(0);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [botSlide, setBotSlide] = useState<SlideAnimation | null>(null);
  const [waitingForBot, setWaitingForBot] = useState(false);
  const [dragFrom, setDragFrom] = useState<SquareId | null>(null);
  const [bestStars, setBestStars] = useState(0);

  useEffect(() => {
    setBestStars(parseInt(localStorage.getItem(storageKey) ?? "0", 10));
  }, [storageKey]);

  const validMoves = useMemo(() => {
    if (!selectedSquare) return [];
    return getLegalMoves(selectedSquare, board, "w");
  }, [selectedSquare, board]);

  const dragValidMoves = useMemo(() => {
    if (!dragFrom) return [];
    return getLegalMoves(dragFrom, board, "w");
  }, [dragFrom, board]);

  const stars = mistakes === 0 ? 3 : mistakes === 1 ? 2 : 1;

  const makeBotMove = useCallback((currentBoard: BoardState) => {
    setWaitingForBot(true);
    setTimeout(() => {
      const move = pickDefenseMove(currentBoard);
      if (!move) {
        setWaitingForBot(false);
        return;
      }
      const piece = currentBoard.pieces.get(move.from)!;
      setBotSlide({
        piece: piece.piece,
        color: piece.color,
        from: move.from,
        to: move.to,
      });
      const newBoard = applyEndgameMove(currentBoard, move.from, move.to);
      setBoard(newBoard);
      setTimeout(() => {
        setBotSlide(null);
        setWaitingForBot(false);
      }, 500);
    }, 400);
  }, []);

  const executeMove = useCallback(
    (from: SquareId, to: SquareId) => {
      const validation = validateEndgameMove(board, from, to);
      if (!validation.valid) {
        setMistakes((m) => m + 1);
        setFeedback(validation.reason ?? "Invalid move");
        setSelectedSquare(null);
        return;
      }

      const newBoard = applyEndgameMove(board, from, to);
      setBoard(newBoard);
      setSelectedSquare(null);
      setFeedback(null);

      if (validation.checkmate) {
        setResult("won");
        const s = mistakes === 0 ? 3 : mistakes === 1 ? 2 : 1;
        const prev = parseInt(localStorage.getItem(storageKey) ?? "0", 10);
        if (s > prev) {
          localStorage.setItem(storageKey, s.toString());
          setBestStars(s);
        }
        return;
      }

      makeBotMove(newBoard);
    },
    [board, makeBotMove, mistakes, storageKey],
  );

  const handleSquareClick = useCallback(
    (sq: SquareId) => {
      if (result !== "playing" || waitingForBot) return;

      if (!selectedSquare) {
        const p = board.pieces.get(sq);
        if (p && p.color === "w") {
          setSelectedSquare(sq);
          setFeedback(null);
        }
        return;
      }

      if (sq === selectedSquare) {
        setSelectedSquare(null);
        return;
      }

      const target = board.pieces.get(sq);
      if (target && target.color === "w") {
        setSelectedSquare(sq);
        return;
      }

      const legal = getLegalMoves(selectedSquare, board, "w");
      if (!legal.includes(sq)) {
        setSelectedSquare(null);
        return;
      }

      executeMove(selectedSquare, sq);
    },
    [board, selectedSquare, result, waitingForBot, executeMove],
  );

  const handleDrop = useCallback(
    (from: SquareId, to: SquareId) => {
      if (result !== "playing" || waitingForBot || from === to) return;
      const p = board.pieces.get(from);
      if (!p || p.color !== "w") return;
      const legal = getLegalMoves(from, board, "w");
      if (!legal.includes(to)) return;
      executeMove(from, to);
    },
    [board, result, waitingForBot, executeMove],
  );

  const onDragStart = useCallback(
    (sq: SquareId) => {
      if (result !== "playing" || waitingForBot) return;
      setDragFrom(sq);
    },
    [result, waitingForBot],
  );

  const onDragEnd = useCallback(() => {
    setDragFrom(null);
  }, []);

  const reset = useCallback(() => {
    setBoard(createBoardState(generatePosition(type)));
    setSelectedSquare(null);
    setResult("playing");
    setMistakes(0);
    setFeedback(null);
    setBotSlide(null);
    setWaitingForBot(false);
    setDragFrom(null);
  }, [type]);

  return (
    <div className="flex flex-col items-center gap-4 max-w-2xl mx-auto">
      <div className="text-center">
        <h2 className="text-xl font-bold mb-1">{info.name}</h2>
        <p className="text-muted">
          {result === "won"
            ? "Checkmate — you win!"
            : waitingForBot
              ? "Opponent is thinking..."
              : info.description}
        </p>
      </div>

      <div className="relative w-full flex justify-center">
        <Board
          board={board}
          selectedSquare={selectedSquare}
          validMoves={validMoves}
          targets={[]}
          reachedTargets={[]}
          dragValidMoves={dragValidMoves}
          onSquareClick={handleSquareClick}
          onDrop={handleDrop}
          onDragStart={onDragStart}
          onDragEnd={onDragEnd}
          opponentSlide={botSlide}
        />
      </div>

      {feedback && result === "playing" && (
        <p className="text-red-400 text-sm font-medium">{feedback}</p>
      )}

      {result === "won" && (
        <div className="flex flex-col items-center gap-3 animate-fade-in">
          <StarRating stars={stars} size="lg" />
          <p className="text-sm text-muted">
            {mistakes === 0
              ? "Perfect — no mistakes!"
              : `${mistakes} mistake${mistakes > 1 ? "s" : ""}`}
          </p>
          {bestStars > 0 && bestStars > stars && (
            <p className="text-xs text-faint">Best: {bestStars} stars</p>
          )}
          <button
            onClick={reset}
            className="px-6 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
          >
            New Position
          </button>
        </div>
      )}
    </div>
  );
}

// src/lib/components/endgame/MateTrainer.svelte
<script lang="ts">
  import Board from '$lib/components/board/Board.svelte';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';
  import { type BoardState, type SquareId, createBoardState } from '$lib/logic/types';
  import { getLegalMoves } from '$lib/logic/attacks';
  import {
    type MateEndgameType,
    ENDGAME_INFO,
    generatePosition,
    validateEndgameMove,
    applyEndgameMove,
    pickDefenseMove,
  } from '$lib/logic/endgame';
  import type { SlideAnimation } from '$lib/state/use-puzzle.svelte';

  interface Props {
    type: MateEndgameType;
  }

  let { type }: Props = $props();

  const info = ENDGAME_INFO[type];
  const storageKey = `endings-${type}-best-stars`;

  /* ── State ────────────────────────────────────── */

  let board = $state<BoardState>(createBoardState(generatePosition(type)));
  let selectedSquare = $state<SquareId | null>(null);
  let result = $state<'playing' | 'won'>('playing');
  let mistakes = $state(0);
  let feedback = $state<string | null>(null);
  let botSlide = $state<SlideAnimation | null>(null);
  let waitingForBot = $state(false);
  let dragFrom = $state<SquareId | null>(null);
  let bestStars = $state(0);

  $effect(() => {
    bestStars = parseInt(localStorage.getItem(storageKey) ?? '0', 10);
  });

  let validMoves = $derived.by(() => {
    if (!selectedSquare) return [];
    return getLegalMoves(selectedSquare, board, 'w');
  });

  let dragValidMoves = $derived.by(() => {
    if (!dragFrom) return [];
    return getLegalMoves(dragFrom, board, 'w');
  });

  let stars = $derived(mistakes === 0 ? 3 : mistakes === 1 ? 2 : 1);

  let statusText = $derived.by(() => {
    if (result === 'won') return 'Checkmate \u2014 you win!';
    if (waitingForBot) return 'Opponent is thinking...';
    return info.description;
  });

  /* ── Bot move ─────────────────────────────────── */

  function makeBotMove(currentBoard: BoardState) {
    waitingForBot = true;
    setTimeout(() => {
      const move = pickDefenseMove(currentBoard);
      if (!move) {
        waitingForBot = false;
        return;
      }
      const piece = currentBoard.pieces.get(move.from)!;
      botSlide = {
        piece: piece.piece,
        color: piece.color,
        from: move.from,
        to: move.to,
      };
      const newBoard = applyEndgameMove(currentBoard, move.from, move.to);
      board = newBoard;
      setTimeout(() => {
        botSlide = null;
        waitingForBot = false;
      }, 500);
    }, 400);
  }

  /* ── Execute player move ──────────────────────── */

  function executeMove(from: SquareId, to: SquareId) {
    const validation = validateEndgameMove(board, from, to);
    if (!validation.valid) {
      mistakes += 1;
      feedback = validation.reason ?? 'Invalid move';
      selectedSquare = null;
      return;
    }

    const newBoard = applyEndgameMove(board, from, to);
    board = newBoard;
    selectedSquare = null;
    feedback = null;

    if (validation.checkmate) {
      result = 'won';
      const s = mistakes === 0 ? 3 : mistakes === 1 ? 2 : 1;
      const prev = parseInt(localStorage.getItem(storageKey) ?? '0', 10);
      if (s > prev) {
        localStorage.setItem(storageKey, s.toString());
        bestStars = s;
      }
      return;
    }

    makeBotMove(newBoard);
  }

  /* ── Click handling ───────────────────────────── */

  function handleSquareClick(sq: SquareId) {
    if (result !== 'playing' || waitingForBot) return;

    if (!selectedSquare) {
      const p = board.pieces.get(sq);
      if (p && p.color === 'w') {
        selectedSquare = sq;
        feedback = null;
      }
      return;
    }

    if (sq === selectedSquare) {
      selectedSquare = null;
      return;
    }

    const target = board.pieces.get(sq);
    if (target && target.color === 'w') {
      selectedSquare = sq;
      return;
    }

    const legal = getLegalMoves(selectedSquare, board, 'w');
    if (!legal.includes(sq)) {
      selectedSquare = null;
      return;
    }

    executeMove(selectedSquare, sq);
  }

  /* ── Drag-and-drop handling ───────────────────── */

  function handleDrop(from: SquareId, to: SquareId) {
    if (result !== 'playing' || waitingForBot || from === to) return;
    const p = board.pieces.get(from);
    if (!p || p.color !== 'w') return;
    const legal = getLegalMoves(from, board, 'w');
    if (!legal.includes(to)) return;
    executeMove(from, to);
  }

  function onDragStart(sq: SquareId) {
    if (result !== 'playing' || waitingForBot) return;
    dragFrom = sq;
  }

  function onDragEnd() {
    dragFrom = null;
  }

  /* ── Reset ────────────────────────────────────── */

  function reset() {
    board = createBoardState(generatePosition(type));
    selectedSquare = null;
    result = 'playing';
    mistakes = 0;
    feedback = null;
    botSlide = null;
    waitingForBot = false;
    dragFrom = null;
  }
</script>

<div class="mate-trainer">
  <div class="header">
    <h2 class="title">{info.name}</h2>
    <p class="status">{statusText}</p>
  </div>

  <div class="board-wrap">
    <Board
      {board}
      {selectedSquare}
      {validMoves}
      targets={[]}
      reachedTargets={[]}
      {dragValidMoves}
      onSquareClick={handleSquareClick}
      onDrop={handleDrop}
      {onDragStart}
      {onDragEnd}
      opponentSlide={botSlide}
    />
  </div>

  {#if feedback && result === 'playing'}
    <p class="feedback">{feedback}</p>
  {/if}

  {#if result === 'won'}
    <div class="result">
      <StarRating {stars} size="lg" />
      <p class="result-text">
        {#if mistakes === 0}
          Perfect — no mistakes!
        {:else}
          {mistakes} mistake{mistakes > 1 ? 's' : ''}
        {/if}
      </p>
      {#if bestStars > 0 && bestStars > stars}
        <p class="best-text">Best: {bestStars} stars</p>
      {/if}
      <button class="new-position-btn" onclick={reset}>
        New Position
      </button>
    </div>
  {/if}
</div>

<style>
  .mate-trainer {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    padding: 1rem;
    max-width: 42rem;
    margin: 0 auto;
  }

  .header {
    text-align: center;
  }

  .title {
    font-size: 1.25rem;
    font-weight: 700;
    margin: 0 0 0.25rem;
  }

  .status {
    color: #888;
    margin: 0;
  }

  .board-wrap {
    position: relative;
    width: 100%;
    display: flex;
    justify-content: center;
  }

  .feedback {
    color: #f87171;
    font-size: 0.875rem;
    font-weight: 500;
    margin: 0;
  }

  .result {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
    animation: fade-in 0.3s ease-out;
  }

  .result-text {
    font-size: 0.875rem;
    color: #888;
    margin: 0;
  }

  .best-text {
    font-size: 0.75rem;
    color: #666;
    margin: 0;
  }

  .new-position-btn {
    padding: 0.5rem 1.5rem;
    background: #16a34a;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.15s;
  }

  .new-position-btn:hover {
    background: #15803d;
  }

  @keyframes fade-in {
    from {
      opacity: 0;
      transform: translateY(0.5rem);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>
