// src/components/puzzle/PuzzleShell.tsx
"use client";

import { useState, useCallback, useMemo } from "react";
import Board from "@/components/board/Board";
import PuzzleControls from "./PuzzleControls";
import StarRating from "./StarRating";
import SuccessOverlay from "./SuccessOverlay";
import { usePuzzle } from "@/lib/state/use-puzzle";
import { Puzzle } from "@/lib/puzzles/types";
import { SquareId, squareToCoords, coordsToSquare } from "@/lib/logic/types";
import { getValidMoves } from "@/lib/logic/moves";
import { getLegalMoves } from "@/lib/logic/attacks";

interface PuzzleShellProps {
  puzzle: Puzzle;
  onNext?: () => void;
}

export default function PuzzleShell({ puzzle, onNext }: PuzzleShellProps) {
  const {
    board,
    selectedSquare,
    validMoves,
    reachedTargets,
    moveCount,
    isComplete,
    stalemateTrigger,
    wrongMoveSquare,
    opponentSlide,
    stars,
    currentHintIndex,
    handleSquareClick,
    handleDrop,
    reset,
    showHint,
  } = usePuzzle(puzzle);

  const [dragFrom, setDragFrom] = useState<SquareId | null>(null);

  // Compute en passant pawn slide animation (from starting rank to current square)
  const pawnSlideData = useMemo(() => {
    const ep = puzzle.enPassantSquare;
    if (!ep) return null;
    const [epFile, epRank] = squareToCoords(ep);
    // En passant square is on rank 5 (index 2) for black pawns that moved from rank 7→5
    // The pawn itself is one rank behind the EP square (closer to its start)
    const pawnRank = epRank === 2 ? 3 : 4; // rank index: 3=rank5, 4=rank4
    const startRank = epRank === 2 ? 1 : 6; // rank index: 1=rank7, 6=rank2
    const pawnSq = coordsToSquare(epFile, pawnRank);
    const startSq = coordsToSquare(epFile, startRank);
    if (!pawnSq || !startSq) return null;
    return { from: startSq, to: pawnSq };
  }, [puzzle.enPassantSquare]);

  // Show the slide until the player makes their first move
  const showPawnSlide = pawnSlideData && moveCount === 0;

  const isBotMode = puzzle.mode === "checkmate-bot";

  const dragValidMoves = useMemo(() => {
    if (!dragFrom) return [];
    const p = board.pieces.get(dragFrom);
    if (!p || p.color !== "w" || (!isBotMode && p.piece !== puzzle.piece)) return [];
    return isBotMode
      ? getLegalMoves(dragFrom, board, "w")
      : getValidMoves(p.piece, dragFrom, board, "w");
  }, [dragFrom, board, puzzle.piece, isBotMode]);

  const onDragStart = useCallback((sq: SquareId) => {
    setDragFrom(sq);
  }, []);

  const onDragEnd = useCallback(() => {
    setDragFrom(null);
  }, []);

  return (
    <div className="flex flex-col items-center gap-4 p-4 max-w-2xl mx-auto">
      {/* Instruction */}
      <div className="text-center">
        <h2 className="text-xl font-bold mb-1">{puzzle.title}</h2>
        <p className="text-muted">{puzzle.instruction}</p>
      </div>

      {/* Move counter */}
      <div className="text-sm text-faint">
        Moves: {moveCount}
        {puzzle.maxMoves && ` / ${puzzle.maxMoves}`}
      </div>

      {/* Board */}
      <div className="relative w-full flex justify-center">
        <Board
          board={board}
          selectedSquare={selectedSquare}
          validMoves={validMoves}
          targets={puzzle.arrows ? [] : puzzle.targets}
          reachedTargets={reachedTargets}
          dragValidMoves={dragValidMoves}
          draggablePiece={isBotMode ? undefined : puzzle.piece}
          onSquareClick={handleSquareClick}
          onDrop={handleDrop}
          onDragStart={onDragStart}
          onDragEnd={onDragEnd}
          pawnSlide={showPawnSlide ? pawnSlideData : undefined}
          wrongMoveSquare={wrongMoveSquare}
          opponentSlide={opponentSlide}
          arrows={moveCount === 0 ? puzzle.arrows : undefined}
        />
        {isComplete && (
          <SuccessOverlay stars={stars} onNext={onNext} onRetry={reset} />
        )}
      </div>

      {/* Stalemate warning */}
      {stalemateTrigger && (
        <div className="bg-red-900/40 border border-red-500/50 rounded-lg px-4 py-3 text-red-200 text-sm text-center">
          <strong>Stalemate!</strong> The opponent has no legal moves but isn&apos;t in check. That&apos;s a draw, not a win.
          <button onClick={reset} className="ml-2 underline font-medium">Try again</button>
        </div>
      )}

      {/* Hint display */}
      {currentHintIndex >= 0 && puzzle.hints && puzzle.hints[currentHintIndex] && (
        <div className="bg-amber-900/40 border border-amber-500/50 rounded-lg px-4 py-2 text-amber-200 text-sm">
          Hint: {puzzle.hints[currentHintIndex]}
        </div>
      )}

      {/* Controls */}
      <PuzzleControls
        onReset={reset}
        onHint={puzzle.hints?.length ? showHint : undefined}
      />

      {/* Star thresholds info */}
      <div className="flex gap-4 text-xs text-faint">
        <span><StarRating stars={3} size="sm" /> {puzzle.starThresholds.three} moves</span>
        <span><StarRating stars={2} size="sm" /> {puzzle.starThresholds.two} moves</span>
        <span><StarRating stars={1} size="sm" /> {puzzle.starThresholds.one} moves</span>
      </div>
    </div>
  );
}

// src/lib/components/puzzle/PuzzleShell.svelte
<script lang="ts">
  import Board from '$lib/components/board/Board.svelte';
  import PuzzleControls from './PuzzleControls.svelte';
  import StarRating from './StarRating.svelte';
  import SuccessOverlay from './SuccessOverlay.svelte';
  import { createPuzzleState } from '$lib/state/use-puzzle.svelte';
  import type { Puzzle } from '$lib/puzzles/types';
  import type { SquareId } from '$lib/logic/types';

  interface Props {
    puzzle: Puzzle;
    onNext?: () => void;
    nextLabel?: string;
  }
  let { puzzle, onNext, nextLabel }: Props = $props();

  let ps = $derived(createPuzzleState(puzzle));

  let dragFrom = $state<SquareId | null>(null);

  let isRoute = $derived(puzzle.type === 'route');
  let isConversion = $derived(puzzle.type === 'conversion');

  let dragValidMoves = $derived.by(() => {
    if (!dragFrom) return [];
    return ps.getMovesFrom(dragFrom);
  });

  // Route puzzles render wall pieces as brick walls
  let obstacles = $derived.by(() => {
    if (puzzle.type !== 'route') return [];
    const pp = puzzle.playerPiece;
    if (pp === 'P') return [];
    const result: SquareId[] = [];
    for (const [sq, p] of ps.board.pieces) {
      if (p.color === 'w' && p.piece !== pp) {
        result.push(sq);
      }
    }
    return result;
  });

  // Targets (stars) only for route puzzles
  let targets = $derived(puzzle.type === 'route' ? puzzle.stars : [] as SquareId[]);

  // Draggable piece restriction — route: only playerPiece; others: any white piece
  let draggablePiece = $derived(puzzle.type === 'route' ? puzzle.playerPiece : undefined);

  // Show move counter for route and conversion
  let showMoveCounter = $derived(puzzle.type === 'route' || puzzle.type === 'conversion');

  // Star thresholds — always available
  let thresholds = $derived.by(() => {
    if (puzzle.type === 'route' || puzzle.type === 'conversion') return puzzle.starThresholds;
    return puzzle.starThresholds ?? null;
  });

  function onDragStart(sq: SquareId) { dragFrom = sq; }
  function onDragEnd() { dragFrom = null; }
</script>

<div class="shell">
  <!-- Instruction -->
  <div class="header">
    <h2 class="title">{puzzle.title}</h2>
    <p class="instruction">{puzzle.instruction}</p>
  </div>

  <!-- Move counter -->
  {#if showMoveCounter && thresholds}
    <div class="move-counter">
      Moves: {ps.moveCount} / {thresholds.three}
    </div>
  {/if}

  <!-- Board -->
  <div class="board-wrapper">
    <Board
      board={ps.board}
      selectedSquare={ps.selectedSquare}
      validMoves={ps.validMoves}
      {targets}
      reachedTargets={ps.reachedTargets}
      {dragValidMoves}
      {draggablePiece}
      onSquareClick={ps.handleSquareClick}
      onDrop={ps.handleDrop}
      {onDragStart}
      {onDragEnd}
      wrongMoveSquare={ps.wrongMoveSquare}
      opponentSlide={ps.opponentSlide}
      arrows={ps.arrows.length > 0 ? ps.arrows : undefined}
      highlights={ps.highlights.length > 0 ? ps.highlights : undefined}
      {obstacles}
    />
    {#if ps.isComplete}
      <SuccessOverlay stars={ps.stars} {onNext} onRetry={ps.reset} {nextLabel} />
    {/if}
  </div>

  <!-- Stalemate warning -->
  {#if ps.stalemateTrigger}
    <div class="stalemate-warning">
      <strong>Stalemate!</strong> The opponent has no legal moves but isn't in check. That's a draw, not a win.
      <button class="stalemate-retry" onclick={ps.reset}>Try again</button>
    </div>
  {/if}

  <!-- Hint display -->
  {#if ps.currentHintIndex >= 0 && puzzle.hints?.[ps.currentHintIndex]}
    <div class="hint-box">
      Hint: {puzzle.hints[ps.currentHintIndex]}
    </div>
  {/if}

  <!-- Controls -->
  <PuzzleControls
    onReset={ps.reset}
    onHint={puzzle.hints?.length ? ps.showHint : undefined}
  />

  <!-- Star thresholds -->
  {#if showMoveCounter && thresholds}
    <div class="thresholds">
      <span><StarRating stars={3} size="sm" /> {thresholds.three} moves</span>
      <span><StarRating stars={2} size="sm" /> {thresholds.two} moves</span>
      <span><StarRating stars={1} size="sm" /> {thresholds.one} moves</span>
    </div>
  {/if}
</div>

<style>
  .shell {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    padding: 1rem;
    max-width: 42rem;
    max-height: 100dvh;
    overflow: hidden;
    margin: 0 auto;
  }
  .header { text-align: center; }
  .title { font-size: 1.25rem; font-weight: bold; margin-bottom: 0.25rem; }
  .instruction { color: var(--text-muted); }
  .move-counter { font-size: 0.875rem; color: var(--text-faint); }
  .board-wrapper { position: relative; width: 100%; display: flex; justify-content: center; }
  .stalemate-warning {
    background: rgba(127, 29, 29, 0.4);
    border: 1px solid rgba(239, 68, 68, 0.5);
    border-radius: 0.5rem;
    padding: 0.75rem 1rem;
    color: #fca5a5;
    font-size: 0.875rem;
    text-align: center;
  }
  .stalemate-retry {
    margin-left: 0.5rem;
    text-decoration: underline;
    font-weight: 500;
    background: none;
    border: none;
    color: inherit;
    cursor: pointer;
  }
  .hint-box {
    background: rgba(120, 53, 15, 0.4);
    border: 1px solid rgba(245, 158, 11, 0.5);
    border-radius: 0.5rem;
    padding: 0.5rem 1rem;
    color: #fcd34d;
    font-size: 0.875rem;
  }
  .thresholds {
    display: flex;
    gap: 1rem;
    font-size: 0.75rem;
    color: var(--text-faint);
  }
  .thresholds span {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
  }
</style>
