// src/routes/board/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';

  let coordStars = $state(0);

  onMount(() => {
    coordStars = parseInt(localStorage.getItem('coord-best-stars') ?? '0', 10);
  });
</script>

<main class="page">
  <a href="/" class="back-link">&larr; Back to home</a>

  <div class="page-header">
    <div class="board-icon">e4</div>
    <div>
      <h1>The Board</h1>
      <p class="muted">Learn the board and set up the pieces.</p>
    </div>
  </div>

  <div class="item-list">
    <a href="/board/coordinates" class="item">
      <div class="item-left">
        <div class="board-icon-sm">e4</div>
        <div>
          <h3>Name the Square</h3>
          <p class="item-desc">Click the right square before time runs out!</p>
        </div>
      </div>
      <div class="item-right">
        {#if coordStars > 0}<StarRating stars={coordStars} size="sm" />{/if}
      </div>
    </a>

    <a href="/setup" class="item">
      <div class="item-left">
        <div class="setup-icons">
          <img src="/pieces/wK.svg" alt="Setup" class="setup-icon" />
          <img src="/pieces/wQ.svg" alt="Setup" class="setup-icon overlap" />
        </div>
        <div>
          <h3>Place the Pieces</h3>
          <p class="item-desc">Put each piece on its starting square.</p>
        </div>
      </div>
      <span class="stat">7 stages</span>
    </a>
  </div>
</main>

<style>
  .page { min-height: 100vh; padding: 1.5rem; max-width: 42rem; margin: 0 auto; }
  .back-link { font-size: 0.875rem; color: var(--text-muted); display: inline-block; margin-bottom: 1rem; }
  .back-link:hover { color: var(--foreground); }
  .muted { color: var(--text-muted); }

  .page-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 2rem; }
  .page-header h1 { font-size: 1.875rem; font-weight: bold; }

  .board-icon {
    width: 4rem; height: 4rem; border-radius: 0.25rem;
    background: #7a9e6e; border: 2px solid #d4c4a0;
    display: flex; align-items: center; justify-content: center;
    font-size: 1.5rem; font-weight: bold; color: #d4c4a0;
  }
  .board-icon-sm {
    width: 2.5rem; height: 2.5rem; border-radius: 0.25rem;
    background: #7a9e6e; border: 2px solid #d4c4a0;
    display: flex; align-items: center; justify-content: center;
    font-size: 0.875rem; font-weight: bold; color: #d4c4a0;
  }

  .setup-icons { width: 2.5rem; height: 2.5rem; display: flex; align-items: center; justify-content: center; }
  .setup-icon { width: 1.5rem; height: 1.5rem; }
  .setup-icon.overlap { margin-left: -0.25rem; }

  .item-list { display: flex; flex-direction: column; gap: 0.75rem; }
  .item {
    display: flex; align-items: center; justify-content: space-between;
    padding: 1.25rem; border-radius: 0.75rem;
    border: 1px solid var(--card-border); background: var(--card-bg);
    transition: all 0.15s;
  }
  .item:hover { border-color: rgba(240, 230, 204, 0.3); box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); }
  .item-left { display: flex; align-items: center; gap: 1rem; }
  .item-left h3 { font-weight: bold; }
  .item-desc { font-size: 0.875rem; color: var(--text-muted); }
  .item-right { text-align: right; }
  .stat { font-size: 0.75rem; color: var(--text-faint); }
</style>

// src/app/board/page.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import StarRating from "@/components/puzzle/StarRating";

export default function BoardPage() {
  const [coordStars, setCoordStars] = useState(0);

  useEffect(() => {
    setCoordStars(parseInt(localStorage.getItem("coord-best-stars") ?? "0", 10));
  }, []);

  return (
    <main className="min-h-screen p-6 max-w-2xl mx-auto">
      <Link href="/" className="text-sm text-muted hover:text-foreground mb-4 inline-block">
        &larr; Back to home
      </Link>

      <div className="flex items-center gap-4 mb-8">
        <div className="w-16 h-16 rounded bg-[#7a9e6e] border-2 border-[#d4c4a0] flex items-center justify-center text-2xl font-bold text-[#d4c4a0]">
          e4
        </div>
        <div>
          <h1 className="text-3xl font-bold">The Board</h1>
          <p className="text-muted">Learn the board and set up the pieces.</p>
        </div>
      </div>

      <div className="space-y-3">
        <Link
          href="/board/coordinates"
          className="flex items-center justify-between p-5 rounded-xl border border-card-border bg-card hover:border-foreground/30 hover:shadow-lg transition-all"
        >
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded bg-[#7a9e6e] border-2 border-[#d4c4a0] flex items-center justify-center text-sm font-bold text-[#d4c4a0]">
              e4
            </div>
            <div>
              <h3 className="font-bold">Name the Square</h3>
              <p className="text-sm text-muted">Click the right square before time runs out!</p>
            </div>
          </div>
          <div className="text-right">
            {coordStars > 0 && <StarRating stars={coordStars} size="sm" />}
          </div>
        </Link>

        <Link
          href="/setup"
          className="flex items-center justify-between p-5 rounded-xl border border-card-border bg-card hover:border-foreground/30 hover:shadow-lg transition-all"
        >
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 flex items-center justify-center">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/pieces/wK.svg" alt="Setup" className="w-6 h-6 -mr-0.5" />
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/pieces/wQ.svg" alt="Setup" className="w-6 h-6 -ml-0.5" />
            </div>
            <div>
              <h3 className="font-bold">Place the Pieces</h3>
              <p className="text-sm text-muted">Put each piece on its starting square.</p>
            </div>
          </div>
          <span className="text-xs text-faint">7 stages</span>
        </Link>
      </div>
    </main>
  );
}
