// src/components/blindfold/WhatChanged.tsx
"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import StarRating from "@/components/puzzle/StarRating";

const LIGHT = "#d4c4a0";
const DARK = "#7a9e6e";

type PieceColor = "w" | "b";
type PieceKind = "K" | "Q" | "R" | "B" | "N" | "P";

interface PiecePlacement {
  piece: PieceKind;
  color: PieceColor;
  square: string;
}

interface Challenge {
  before: PiecePlacement[];
  after: PiecePlacement[];
  movedPiece: PiecePlacement;
  movedTo: string;
  answer: string; // "Xsq → sq" description
}

const PIECE_POOL: { piece: PieceKind; color: PieceColor }[] = [
  { piece: "K", color: "w" }, { piece: "Q", color: "w" }, { piece: "R", color: "w" },
  { piece: "B", color: "w" }, { piece: "N", color: "w" }, { piece: "P", color: "w" },
  { piece: "K", color: "b" }, { piece: "Q", color: "b" }, { piece: "R", color: "b" },
  { piece: "B", color: "b" }, { piece: "N", color: "b" }, { piece: "P", color: "b" },
];

function randomSquare(): string {
  const f = Math.floor(Math.random() * 8);
  const r = Math.floor(Math.random() * 8);
  return String.fromCharCode(97 + f) + (r + 1);
}

function generateChallenge(numPieces: number): Challenge {
  const usedSquares = new Set<string>();
  const placements: PiecePlacement[] = [];

  for (let i = 0; i < numPieces; i++) {
    let sq: string;
    do { sq = randomSquare(); } while (usedSquares.has(sq));
    usedSquares.add(sq);
    const p = PIECE_POOL[Math.floor(Math.random() * PIECE_POOL.length)];
    placements.push({ ...p, square: sq });
  }

  // Pick a random piece to move
  const moveIdx = Math.floor(Math.random() * placements.length);
  const movedPiece = placements[moveIdx];
  let newSq: string;
  do { newSq = randomSquare(); } while (usedSquares.has(newSq));

  const after = placements.map((p, i) =>
    i === moveIdx ? { ...p, square: newSq } : { ...p }
  );

  const colorName = movedPiece.color === "w" ? "White" : "Black";
  return {
    before: placements,
    after,
    movedPiece,
    movedTo: newSq,
    answer: `${colorName} ${movedPiece.piece} ${movedPiece.square} → ${newSq}`,
  };
}

function sqToCoords(sq: string): [number, number] {
  return [sq.charCodeAt(0) - 97, 8 - parseInt(sq[1])];
}

function PositionBoard({ placements, size, highlight }: {
  placements: PiecePlacement[];
  size: number;
  highlight?: { from?: string; to?: string };
}) {
  const S = size;
  const B = S * 8;

  return (
    <svg viewBox={`0 0 ${B} ${B}`} className="w-full max-w-[280px] sm:max-w-[320px]">
      {Array.from({ length: 8 }, (_, ri) =>
        Array.from({ length: 8 }, (_, fi) => {
          const isLight = (fi + ri) % 2 === 0;
          const sqName = String.fromCharCode(97 + fi) + (8 - ri);
          let fill = isLight ? LIGHT : DARK;
          if (highlight?.from === sqName) fill = "#f0a0a0";
          if (highlight?.to === sqName) fill = "#a3d9a3";
          return <rect key={`${fi}-${ri}`} x={fi * S} y={ri * S} width={S} height={S} fill={fill} />;
        })
      )}
      {placements.map((p, i) => {
        const [f, r] = sqToCoords(p.square);
        return (
          <image
            key={i}
            href={`/pieces/${p.color}${p.piece}.svg`}
            x={f * S + S * 0.1}
            y={r * S + S * 0.1}
            width={S * 0.8}
            height={S * 0.8}
          />
        );
      })}
    </svg>
  );
}

function getStars(correct: number, total: number): number {
  const pct = total > 0 ? correct / total : 0;
  if (pct >= 0.9) return 3;
  if (pct >= 0.7) return 2;
  if (pct >= 0.5) return 1;
  return 0;
}

type Phase = "idle" | "showing" | "guessing" | "feedback" | "done";

export default function WhatChanged() {
  const [phase, setPhase] = useState<Phase>("idle");
  const [level, setLevel] = useState(4); // starting piece count
  const [challenge, setChallenge] = useState<Challenge | null>(null);
  const [input, setInput] = useState("");
  const [correct, setCorrect] = useState(0);
  const [total, setTotal] = useState(0);
  const [round, setRound] = useState(0);
  const [isCorrect, setIsCorrect] = useState(false);
  const [bestStars, setBestStars] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const showTimerRef = useRef<ReturnType<typeof setTimeout>>(null);

  const ROUNDS = 10;
  const SHOW_TIME = 4000; // ms to memorize

  useEffect(() => {
    setBestStars(parseInt(localStorage.getItem("blindfold-changed-best-stars") ?? "0", 10));
  }, []);

  const startGame = useCallback(() => {
    const ch = generateChallenge(level);
    setChallenge(ch);
    setPhase("showing");
    setCorrect(0);
    setTotal(0);
    setRound(1);
    showTimerRef.current = setTimeout(() => {
      setPhase("guessing");
    }, SHOW_TIME);
  }, [level]);

  useEffect(() => {
    if (phase === "guessing") inputRef.current?.focus();
  }, [phase]);

  useEffect(() => {
    return () => {
      if (showTimerRef.current) clearTimeout(showTimerRef.current);
    };
  }, []);

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault();
      if (!challenge || phase !== "guessing") return;
      const sq = input.trim().toLowerCase();
      setInput("");

      // Accept the moved-to square as the answer
      const right = sq === challenge.movedTo || sq === challenge.movedPiece.square;
      setIsCorrect(right);
      if (right) setCorrect((c) => c + 1);
      setTotal((t) => t + 1);
      setPhase("feedback");
    },
    [challenge, input, phase],
  );

  const nextRound = useCallback(() => {
    if (round >= ROUNDS) {
      const stars = getStars(correct + (isCorrect ? 0 : 0), total); // already counted
      if (stars > bestStars) {
        localStorage.setItem("blindfold-changed-best-stars", String(stars));
        setBestStars(stars);
      }
      setPhase("done");
      return;
    }
    const ch = generateChallenge(level);
    setChallenge(ch);
    setPhase("showing");
    setRound((r) => r + 1);
    showTimerRef.current = setTimeout(() => {
      setPhase("guessing");
    }, SHOW_TIME);
  }, [round, level, correct, total, bestStars, isCorrect]);

  const stars = getStars(correct, total);

  if (phase === "idle") {
    return (
      <div className="flex flex-col items-center gap-6 max-w-md mx-auto text-center">
        <h2 className="text-xl font-bold">What Changed?</h2>
        <p className="text-muted">
          Memorize a position, then identify what moved. {ROUNDS} rounds — type the square something moved to (or from).
        </p>
        <div className="flex items-center gap-4">
          <label className="text-sm text-muted">Pieces:</label>
          {[4, 6, 8].map((n) => (
            <button
              key={n}
              onClick={() => setLevel(n)}
              className={`px-3 py-1 rounded-lg text-sm font-medium transition-colors ${
                level === n ? "bg-green-600 text-white" : "border border-card-border text-faint hover:text-foreground"
              }`}
            >
              {n}
            </button>
          ))}
        </div>
        {bestStars > 0 && (
          <div className="text-sm text-faint">
            <StarRating stars={bestStars} size="sm" />
          </div>
        )}
        <button
          onClick={startGame}
          className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold text-lg hover:bg-green-700 transition-colors"
        >
          Start
        </button>
      </div>
    );
  }

  if (phase === "done") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <h2 className="text-xl font-bold">Complete!</h2>
        <p className="text-3xl font-bold">{correct}/{total} correct</p>
        {stars > 0 && <StarRating stars={stars} size="lg" />}
        <button
          onClick={() => setPhase("idle")}
          className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition-colors"
        >
          Play Again
        </button>
      </div>
    );
  }

  if (!challenge) return null;

  if (phase === "showing") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <div className="text-sm text-faint">Round {round}/{ROUNDS} — Memorize this position!</div>
        <PositionBoard placements={challenge.before} size={40} />
        <div className="text-sm text-muted animate-pulse">Studying...</div>
      </div>
    );
  }

  if (phase === "guessing") {
    return (
      <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
        <div className="text-sm text-faint">Round {round}/{ROUNDS} — What moved?</div>
        <PositionBoard placements={challenge.after} size={40} />
        <p className="text-sm text-muted">One piece moved. Type the square it moved <strong>to</strong> or <strong>from</strong>.</p>
        <form onSubmit={handleSubmit} className="flex gap-2 w-full max-w-[200px]">
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Square..."
            maxLength={2}
            className="flex-1 px-4 py-2 rounded-lg border border-card-border bg-card text-foreground font-mono text-lg text-center focus:outline-none focus:border-foreground/40"
            autoComplete="off"
            autoCapitalize="off"
          />
          <button
            type="submit"
            className="px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
          >
            Go
          </button>
        </form>
      </div>
    );
  }

  // feedback
  return (
    <div className="flex flex-col items-center gap-4 max-w-md mx-auto text-center">
      <div className="text-sm text-faint">Round {round}/{ROUNDS}</div>
      <p className={`text-xl font-bold ${isCorrect ? "text-green-400" : "text-red-400"}`}>
        {isCorrect ? "Correct!" : "Wrong!"}
      </p>
      <p className="text-sm text-muted">{challenge.answer}</p>
      <PositionBoard
        placements={challenge.after}
        size={40}
        highlight={{ from: challenge.movedPiece.square, to: challenge.movedTo }}
      />
      <button
        onClick={nextRound}
        className="px-6 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
      >
        {round >= ROUNDS ? "See Results" : "Next"}
      </button>
    </div>
  );
}

// src/lib/components/blindfold/WhatChanged.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import StarRating from '$lib/components/puzzle/StarRating.svelte';

  const LIGHT = '#d4c4a0';
  const DARK = '#7a9e6e';

  type PieceColor = 'w' | 'b';
  type PieceKind = 'K' | 'Q' | 'R' | 'B' | 'N' | 'P';

  interface PiecePlacement {
    piece: PieceKind;
    color: PieceColor;
    square: string;
  }

  interface Challenge {
    before: PiecePlacement[];
    after: PiecePlacement[];
    movedPiece: PiecePlacement;
    movedTo: string;
    answer: string;
  }

  const PIECE_POOL: { piece: PieceKind; color: PieceColor }[] = [
    { piece: 'K', color: 'w' }, { piece: 'Q', color: 'w' }, { piece: 'R', color: 'w' },
    { piece: 'B', color: 'w' }, { piece: 'N', color: 'w' }, { piece: 'P', color: 'w' },
    { piece: 'K', color: 'b' }, { piece: 'Q', color: 'b' }, { piece: 'R', color: 'b' },
    { piece: 'B', color: 'b' }, { piece: 'N', color: 'b' }, { piece: 'P', color: 'b' },
  ];

  function randomSquare(): string {
    const f = Math.floor(Math.random() * 8);
    const r = Math.floor(Math.random() * 8);
    return String.fromCharCode(97 + f) + (r + 1);
  }

  function generateChallenge(numPieces: number): Challenge {
    const usedSquares = new Set<string>();
    const placements: PiecePlacement[] = [];

    for (let i = 0; i < numPieces; i++) {
      let sq: string;
      do { sq = randomSquare(); } while (usedSquares.has(sq));
      usedSquares.add(sq);
      const p = PIECE_POOL[Math.floor(Math.random() * PIECE_POOL.length)];
      placements.push({ ...p, square: sq });
    }

    const moveIdx = Math.floor(Math.random() * placements.length);
    const movedPiece = placements[moveIdx];
    let newSq: string;
    do { newSq = randomSquare(); } while (usedSquares.has(newSq));

    const after = placements.map((p, i) =>
      i === moveIdx ? { ...p, square: newSq } : { ...p }
    );

    const colorName = movedPiece.color === 'w' ? 'White' : 'Black';
    return {
      before: placements,
      after,
      movedPiece,
      movedTo: newSq,
      answer: `${colorName} ${movedPiece.piece} ${movedPiece.square} \u2192 ${newSq}`,
    };
  }

  function sqToCoords(sq: string): [number, number] {
    return [sq.charCodeAt(0) - 97, 8 - parseInt(sq[1])];
  }

  function getStars(correct: number, total: number): number {
    const pct = total > 0 ? correct / total : 0;
    if (pct >= 0.9) return 3;
    if (pct >= 0.7) return 2;
    if (pct >= 0.5) return 1;
    return 0;
  }

  const ROUNDS = 10;
  const SHOW_TIME = 4000;
  const SQ_SIZE = 40;
  const BOARD_PX = SQ_SIZE * 8;

  type Phase = 'idle' | 'showing' | 'guessing' | 'feedback' | 'done';

  let phase: Phase = $state('idle');
  let level = $state(4);
  let challenge: Challenge | null = $state(null);
  let input = $state('');
  let correct = $state(0);
  let total = $state(0);
  let round = $state(0);
  let isCorrect = $state(false);
  let bestStars = $state(0);

  let inputEl: HTMLInputElement | null = $state(null);
  let showTimerRef: ReturnType<typeof setTimeout> | null = null;

  onMount(() => {
    bestStars = parseInt(localStorage.getItem('blindfold-changed-best-stars') ?? '0', 10);

    return () => {
      if (showTimerRef) clearTimeout(showTimerRef);
    };
  });

  $effect(() => {
    if (phase === 'guessing' && inputEl) inputEl.focus();
  });

  function startGame() {
    const ch = generateChallenge(level);
    challenge = ch;
    phase = 'showing';
    correct = 0;
    total = 0;
    round = 1;
    showTimerRef = setTimeout(() => {
      phase = 'guessing';
    }, SHOW_TIME);
  }

  function handleSubmit(e: Event) {
    e.preventDefault();
    if (!challenge || phase !== 'guessing') return;
    const sq = input.trim().toLowerCase();
    input = '';

    const right = sq === challenge.movedTo || sq === challenge.movedPiece.square;
    isCorrect = right;
    if (right) correct += 1;
    total += 1;
    phase = 'feedback';
  }

  function nextRound() {
    if (round >= ROUNDS) {
      const stars = getStars(correct, total);
      if (stars > bestStars) {
        localStorage.setItem('blindfold-changed-best-stars', String(stars));
        bestStars = stars;
      }
      phase = 'done';
      return;
    }
    const ch = generateChallenge(level);
    challenge = ch;
    phase = 'showing';
    round += 1;
    showTimerRef = setTimeout(() => {
      phase = 'guessing';
    }, SHOW_TIME);
  }

  function goIdle() {
    phase = 'idle';
  }

  let stars = $derived(getStars(correct, total));

  function squareFill(fi: number, ri: number, highlight?: { from?: string; to?: string }): string {
    const isLight = (fi + ri) % 2 === 0;
    const sqName = String.fromCharCode(97 + fi) + (8 - ri);
    if (highlight?.from === sqName) return '#f0a0a0';
    if (highlight?.to === sqName) return '#a3d9a3';
    return isLight ? LIGHT : DARK;
  }
</script>

<div class="container">
  {#if phase === 'idle'}
    <div class="center-col">
      <h2 class="title">What Changed?</h2>
      <p class="muted">
        Memorize a position, then identify what moved. {ROUNDS} rounds &mdash; type the square something moved to (or from).
      </p>
      <div class="level-picker">
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label class="level-label">Pieces:</label>
        {#each [4, 6, 8] as n}
          <button
            class="level-btn"
            class:level-active={level === n}
            onclick={() => { level = n; }}
          >
            {n}
          </button>
        {/each}
      </div>
      {#if bestStars > 0}
        <div class="best">
          <StarRating stars={bestStars} size="sm" />
        </div>
      {/if}
      <button class="start-btn" onclick={startGame}>Start</button>
    </div>
  {:else if phase === 'done'}
    <div class="center-col">
      <h2 class="title">Complete!</h2>
      <p class="big-score">{correct}/{total} correct</p>
      {#if stars > 0}
        <StarRating {stars} size="lg" />
      {/if}
      <button class="start-btn" onclick={goIdle}>Play Again</button>
    </div>
  {:else if phase === 'showing' && challenge}
    <div class="center-col">
      <div class="round-label">Round {round}/{ROUNDS} &mdash; Memorize this position!</div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg viewBox="0 0 {BOARD_PX} {BOARD_PX}" class="board-svg">
        {#each Array(8) as _, ri}
          {#each Array(8) as _, fi}
            <rect
              x={fi * SQ_SIZE}
              y={ri * SQ_SIZE}
              width={SQ_SIZE}
              height={SQ_SIZE}
              fill={squareFill(fi, ri)}
            />
          {/each}
        {/each}
        {#each challenge.before as p}
          {@const [f, r] = sqToCoords(p.square)}
          <image
            href="/pieces/{p.color}{p.piece}.svg"
            x={f * SQ_SIZE + SQ_SIZE * 0.1}
            y={r * SQ_SIZE + SQ_SIZE * 0.1}
            width={SQ_SIZE * 0.8}
            height={SQ_SIZE * 0.8}
          />
        {/each}
      </svg>
      <div class="studying">Studying...</div>
    </div>
  {:else if phase === 'guessing' && challenge}
    <div class="center-col">
      <div class="round-label">Round {round}/{ROUNDS} &mdash; What moved?</div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg viewBox="0 0 {BOARD_PX} {BOARD_PX}" class="board-svg">
        {#each Array(8) as _, ri}
          {#each Array(8) as _, fi}
            <rect
              x={fi * SQ_SIZE}
              y={ri * SQ_SIZE}
              width={SQ_SIZE}
              height={SQ_SIZE}
              fill={squareFill(fi, ri)}
            />
          {/each}
        {/each}
        {#each challenge.after as p}
          {@const [f, r] = sqToCoords(p.square)}
          <image
            href="/pieces/{p.color}{p.piece}.svg"
            x={f * SQ_SIZE + SQ_SIZE * 0.1}
            y={r * SQ_SIZE + SQ_SIZE * 0.1}
            width={SQ_SIZE * 0.8}
            height={SQ_SIZE * 0.8}
          />
        {/each}
      </svg>
      <p class="muted-sm">One piece moved. Type the square it moved <strong>to</strong> or <strong>from</strong>.</p>
      <form class="input-row" onsubmit={handleSubmit}>
        <input
          bind:this={inputEl}
          type="text"
          bind:value={input}
          placeholder="Square..."
          maxlength={2}
          class="sq-input"
          autocomplete="off"
          autocapitalize="off"
        />
        <button type="submit" class="go-btn">Go</button>
      </form>
    </div>
  {:else if phase === 'feedback' && challenge}
    <div class="center-col">
      <div class="round-label">Round {round}/{ROUNDS}</div>
      <p class="feedback-text" class:correct-text={isCorrect} class:wrong-text={!isCorrect}>
        {isCorrect ? 'Correct!' : 'Wrong!'}
      </p>
      <p class="muted-sm">{challenge.answer}</p>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg viewBox="0 0 {BOARD_PX} {BOARD_PX}" class="board-svg">
        {#each Array(8) as _, ri}
          {#each Array(8) as _, fi}
            <rect
              x={fi * SQ_SIZE}
              y={ri * SQ_SIZE}
              width={SQ_SIZE}
              height={SQ_SIZE}
              fill={squareFill(fi, ri, { from: challenge.movedPiece.square, to: challenge.movedTo })}
            />
          {/each}
        {/each}
        {#each challenge.after as p}
          {@const [f, r] = sqToCoords(p.square)}
          <image
            href="/pieces/{p.color}{p.piece}.svg"
            x={f * SQ_SIZE + SQ_SIZE * 0.1}
            y={r * SQ_SIZE + SQ_SIZE * 0.1}
            width={SQ_SIZE * 0.8}
            height={SQ_SIZE * 0.8}
          />
        {/each}
      </svg>
      <button class="go-btn next-btn" onclick={nextRound}>
        {round >= ROUNDS ? 'See Results' : 'Next'}
      </button>
    </div>
  {/if}
</div>

<style>
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    max-width: 28rem;
    margin: 0 auto;
  }

  .center-col {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    text-align: center;
  }

  .title {
    font-size: 1.25rem;
    font-weight: bold;
  }

  .muted {
    color: var(--text-muted);
  }

  .muted-sm {
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .best {
    font-size: 0.875rem;
    color: var(--text-faint);
  }

  .round-label {
    font-size: 0.875rem;
    color: var(--text-faint);
  }

  .level-picker {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .level-label {
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .level-btn {
    padding: 0.25rem 0.75rem;
    border-radius: 0.5rem;
    font-size: 0.875rem;
    font-weight: 500;
    border: 1px solid var(--card-border);
    background: transparent;
    color: var(--text-faint);
    cursor: pointer;
    transition: color 0.15s, border-color 0.15s;
  }

  .level-btn:hover {
    color: var(--foreground);
  }

  .level-active {
    background: #16a34a;
    color: white;
    border-color: #16a34a;
  }

  .start-btn {
    padding: 0.75rem 2rem;
    background: rgba(255, 248, 230, 0.15);
    color: var(--foreground);
    border: none;
    border-radius: 0.5rem;
    font-weight: bold;
    font-size: 1.125rem;
    cursor: pointer;
    transition: background 0.15s;
  }

  .start-btn:hover {
    background: rgba(255, 248, 230, 0.25);
  }

  .big-score {
    font-size: 1.875rem;
    font-weight: bold;
  }

  .board-svg {
    width: 100%;
    max-width: 280px;
    display: block;
  }

  @media (min-width: 640px) {
    .board-svg {
      max-width: 320px;
    }
  }

  .studying {
    font-size: 0.875rem;
    color: var(--text-muted);
    animation: pulse 2s ease-in-out infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }

  .input-row {
    display: flex;
    gap: 0.5rem;
    width: 100%;
    max-width: 200px;
  }

  .sq-input {
    flex: 1;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    border: 1px solid var(--card-border);
    background: var(--card-bg);
    color: var(--foreground);
    font-family: monospace;
    font-size: 1.125rem;
    text-align: center;
  }

  .sq-input:focus {
    outline: none;
    border-color: rgba(255, 248, 230, 0.4);
  }

  .go-btn {
    padding: 0.5rem 1rem;
    background: #16a34a;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.15s;
  }

  .go-btn:hover {
    background: #15803d;
  }

  .next-btn {
    padding: 0.5rem 1.5rem;
  }

  .feedback-text {
    font-size: 1.25rem;
    font-weight: bold;
  }

  .correct-text {
    color: #4ade80;
  }

  .wrong-text {
    color: #f87171;
  }
</style>
